### ISSUE TITLE
Outputs already assigned to a sub program are still displayed for another sub program

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#1]
Outputs already assigned to a sub program are still displayed for another sub program (see Sélection_2016033010:10:16.png) For example Ooutputs 1.1 are available to be added in sub program 2 whereas they are already assigned to sub program 1.1.

Abyot: This is a little tricky... in one way it makes sense to restrict and I will fix it. But at the same time it could be possible for an output to contribute to more than one sub-program.

Alex:  I added Q83 to confirm that

**Comment by Aleglise** [comment]
An output can contribute to only one sub-program. So it should be preferable to not show it anymore when assigned.

**Comment by abyot** [comment]
@Aleglise This is now fixed.

**Comment by Aleglise** [comment]
Re test KO. (see Program TEST 1459961273620 sub programs)

**Comment by abyot** [comment]
That is because the output is already assigned. The solution is remove the output from one of the sub-programs.

**Comment by Aleglise** [comment]
retest KO.
I've created a Sub progams SP_TEST_03 & 04.
I've added output "Increased addition of value to fisheries value chains" in SP_TEST_03 and this outpout is available and selectable for SP_TEST_04

**Comment by abyot** [comment]
@Aleglise  Under which program did you test this?

**Comment by abyot** [comment]
@Aleglise  Ok now I have found the issue... seems it needs a refresh. selected items are not dynamically removed. If you try to assign again, the output is not available for selection. I will fix it.

**Comment by Aleglise** [comment]
program is Program TEST 02

**Comment by abyot** [comment]
Fixed.

**Comment by Aleglise** [comment]
retest KO. 
Outputs assigned to deleted program are not available (ex. Improved Integrated Soil Fertility Management (ISFM) by Rwandan farmers) whereas they should be.

**Comment by abyot** [comment]
oh, yes. Delete requires refresh ... I will fix it.

**Comment by abyot** [comment]
Fixed.
