### ISSUE TITLE
District level data set not assigned to district level

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#10]
Data set "Water User Associations District Level Annual Dataset" wasn't assigned to district level.
For demo purpose, I assigned it to all districts.

**Comment by Aleglise** [comment]
Same issue with Food & Nutrition Security District level Annual Dataset. Please review every data sets.

**Comment by arunimam** [comment]
All the datasets have been reviewed and assigned at appropriate levels based on part 2 sheet: N = National Level, P = Provincial Level, D = District Level, S = Section Level

1   District & Section  Agricultural Finance District/Section level Annual Dataset
2   District & Section  Agricultural Mechanisation District/Section Level Annual Dataset
3   National    Economic Growth National level Annual Dataset
4   Provincial  Economic Growth Provincial level Annual Dataset
5   District & Section  Extension and Proximity Services for Producers District/Section level 
                                       Annual Dataset
6   National    Extension and Proximity Services for Producers National level Annual Dataset
7   District & Section  Farmer Cooperatives and Organisations District/Section level Annual  
                                        Dataset
8   District    Food & Nutrition Security District level Annual Dataset
9   National&District   Food & Nutrition Security National/District level Half Yearly Dataset
10  District & Section  Improved Health of Livestock District/Section level Annual Dataset
11  National    Institutional Capacity Building National level Annual Dataset
12  District    Livestock Development District/Section level Annual Dataset
13  District & Section  Market-oriented Infrastructure District/Section level Annual Dataset
14  National&District   Monetary Income supported by Agriculture N/D level Annual Dataset
15  Nationa,Provincial&District Poverty Reduction supported by Agriculture N/P/D level Annual Dataset
16  District & Section  Priority Value Chains Fisheries District/Section level Annual Dataset
17  National    Priority Value Chains Food & Export Crops National level Annual Dataset
18  National    Private Investment, Entrepreneurship & Market Access National level Annual Dataset
19  District    Productivity (Crops) District Level Annual Dataset
20  District    Productivity (Livestock) District Level Annual Dataset
21  National    Productivity (Livetsock) National Level Annual Dataset
22  National    Research and Technology Transfer National level Quarterly Dataset
23  District & Section  Seed Development District/Section level Annual Dataset
24  District & Section  Soil Conservation and Land Husbandry District Level Quarterly Dataset
25  District & Section  Soil Fertility and Management District/Section level Annual Dataset
26  District    Water User Associations District Level Annual Dataset
