### ISSUE TITLE
Is there a way to mask sector to end users?

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#106]
Now data entry ois done at disctrict level.

However, MINAGRI plan  to enter data at sector level next year.

To not confuse end users, sector should be hidden for now, as data entry is done from disctrict level only.

**Comment by abyot** [comment]
No, this is not possible at the moment. If users are assigned districts, they will see sectors and anything below.

To avoid confusion, a simple things you could do is don't to assign datasets to sectors.
