### ISSUE TITLE
Datasets to be deleted

### ISSUE THREAD

**Issue by arunimam** [minagri-rwanda/DHIS2-Agriculture#113]
@abyot 

Following datasets needs to be deleted from back end as we are not able to delete them from front end:
1. 04_TEST_Project_ABC Budget execution
2. 04_TEST_Project_ABC Budget forecast
3. 5_Project_TEST_Execution
4. 5_Project_TEST_Forecast
5. 7_TEST_PROJECT Budget Forecast
6. 8_TEST_ProjectABC_Budget Execution
7. 8_TEST_ProjectABC_Budget Forecast
8. 9 TEST Project Execution
9. 9 TEST Project Forecast
10. 9_TEST3-Baseline
11. Agricultural Finance District/Section level Annual Dataset
12. Agricultural Mechanisation District/Section Level Annual Dataset
13. Economic Growth Province level Annual Dataset
14. Extension and Proximity Services for Producers District/Section level Annual Dataset
15. Food & Nutrition Security District level Annual Dataset
16. Food & Nutrition Security National/District level Half Yearly Dataset
17. Institutional Capacity Building National level Annual Dataset
18. Irrigation & Water Managment District Level Annual Dataset
19. LWH Project - Budget Execution
20. LWH Project - Budget Forecast
21. OP1.6b - Increased and sustainable production of livestock commodities
22. OP3.6.1
23. Priority Value Chains Fisheries District/Section level Annual Dataset
24. Seed Development District/Section level Annual Dataset
25. Soil Fertility and Management District/Section level Annual Dataset
26. Sub-program 3.6
27. Sub-program 3.6 targets
28. Test Project - Budget
29. Increased coverage, efficiency and sustainability of soil conservation infrastructure and practices

**Comment by Aleglise** [comment]
@abyot 
About LWH Project - Budget Execution & LWH Project - Budget Forecast:
entered data can be deleted but not the data sets

**Comment by arunimam** [comment]
Ok and what about other datasets

**Comment by arunimam** [comment]
Also facing issue in these three datasets

Baseline (IP) Vision 2020 and EDPRS-2 targets for economic growth and poverty reduction supported by agriculture sector Province Level Annual Dataset
Progress (IP) Vision 2020 and EDPRS-2 targets for economic growth and poverty reduction supported by agriculture sector Province Level Annual Dataset
Target (IP) Vision 2020 and EDPRS-2 targets for economic growth and poverty reduction supported by agriculture sector Province Level Annual Dataset

After creating the custom datasets , when we check in data entry screen it gives exception error

![image](https://cloud.githubusercontent.com/assets/12066960/16924085/1e8bd8da-4d3b-11e6-9212-fe88ae7ce2db.png)

**Comment by arunimam** [comment]
Also don't delete LWH Project - Budget Execution & LWH Project - Budget Forecast datasets

**Comment by abyot** [comment]
Ok, tell me one more time. Except the LWH budget datasets do you want me to delete all datasets listed above?

Also, which values do you want me to delete?

**Comment by Aleglise** [comment]
@abyot Yes. All listed data sets data entries values can be deleted. Please backup in case of.

@arunimam, regarding the other issue (https://github.com/minagri-rwanda/DHIS2-Agriculture/issues/113#issuecomment-233398456), it would be preferable to open a separated issue and to delete the issue comment. 

Please also assign Github to one person.

**Comment by arunimam** [comment]
@abyot Only LWH budget datasets should not be deleted, rest all needs to be deleted

@Aleglise Ok i will raise separate issue for the other issue

**Comment by abyot** [comment]
Data sets 1-18, 21-28 are now deleted.

I am not able to find data set 29.

For those deleted data sets, corresponding values are also removed. Values linked to data sets 19 and 20 are also deleted.

**Comment by arunimam** [comment]
Thanks
