### ISSUE TITLE
Exception Error in data entry screen

### ISSUE THREAD

**Issue by arunimam** [minagri-rwanda/DHIS2-Agriculture#114]
@ Abyot

Facing issue in these three datasets

Baseline (IP) Vision 2020 and EDPRS-2 targets for economic growth and poverty reduction supported by agriculture sector Province Level Annual Dataset
Progress (IP) Vision 2020 and EDPRS-2 targets for economic growth and poverty reduction supported by agriculture sector Province Level Annual Dataset
Target (IP) Vision 2020 and EDPRS-2 targets for economic growth and poverty reduction supported by agriculture sector Province Level Annual Dataset

After creating the custom datasets , when we check in data entry screen it gives exception error

image

**Comment by arunimam** [comment]
![image](https://cloud.githubusercontent.com/assets/12066960/16939825/b37f1e04-4da2-11e6-9b7d-25cda8b957b1.png)

**Comment by abyot** [comment]
This is because the custom form is invalid. We just have to delete and recreate the custom form. 

Below are some of the issues I can think of:
- some strange character in data set / data element names which is conflicting with custom form HTML parsing
- missing category option combos i.e. category option combo assigned to custom form but somehow deleted.

**Comment by Aleglise** [comment]
I cannot access to the data set data entry form for :
Progress (IP) Vision 2020 and EDPRS-2 targets for economic growth and poverty reduction supported by agriculture sector Province Level Annual Dataset
Target (IP) Vision 2020 and EDPRS-2 targets for economic growth and poverty reduction supported by agriculture sector Province Level Annual Dataset
![image](https://cloud.githubusercontent.com/assets/8737709/17461137/94c12ca8-5c81-11e6-89ba-cdff05201d7a.png)

For Baseline (IP) Vision 2020 and EDPRS-2 targets for economic growth and poverty reduction supported by agriculture sector Province Level Annual Dataset
The custom data entry form is empty and lokk wired:
![image](https://cloud.githubusercontent.com/assets/8737709/17461144/ce0632c4-5c81-11e6-94c1-ab9fdda45e77.png)

**Comment by abyot** [comment]
That is because data element names contain a dollar ($) sign.

This is a reserved character in jQuery. Please make sure that we have this and other strange characters removed from both custom form and metadata.

**Comment by arunimam** [comment]
Deleted the special character from data element. 

Created the datasets again. Please check now they are visible in data entry screen

**Comment by Aleglise** [comment]
It is fine now. 
Thank you.
