### ISSUE TITLE
Issue in datasets of Improved capacity of agricultural cooperatives

### ISSUE THREAD

**Issue by arunimam** [minagri-rwanda/DHIS2-Agriculture#116]
There is a different type of issue in these three datasets 

Baseline (OP) Improved capacity of agricultural cooperatives to link farmers efficiently to input and output markets District Level Annual Dataset
Progress (OP) Improved capacity of agricultural cooperatives to link farmers efficiently to input and output markets District Level Annual Dataset
Target (OP) Improved capacity of agricultural cooperatives to link farmers efficiently to input and output markets District Level Annual Dataset

After designing the custom datasets when we check in data entry screen the dataset appears like this

![image](https://cloud.githubusercontent.com/assets/12066960/17067585/0719b1a4-506a-11e6-9b1a-b6d0255f1e68.png)

Even after redesigning the issue reappears

**Comment by Aleglise** [comment]
@arunimam it was a data element naming issue After renaming data element whithout special caracters and having updated the data entry form, this issue is now solved.
