### ISSUE TITLE
OSM Layer not properly managed

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#117]
![image](https://cloud.githubusercontent.com/assets/8737709/17321968/7d8736b6-589b-11e6-9367-0ae44ef615a9.png)

**Comment by abyot** [comment]
Oh ya, this is because of the latest changes in Google GIS API policy... This is a common issue we just faced in across DHIS2. The GIS team is currently trying to figure out a problem. They have said we do not have this problem in 2.24. So upgrading could be one solution.

**Comment by Aleglise** [comment]
Regarding the data capture app, upgrading could also be one solution: https://github.com/dhis2/dhis2-android-datacapture/issues/23

**Comment by Aleglise** [comment]
Can you please assess the risks of a 2.24 upgrade?

**Comment by abyot** [comment]
Yes, right now trying to upgrade. I was kind of pushing task, if not critically needed to avoid it all together. But seems we need it more and more. The thing is I just have to synchronize many things :(

**Comment by Aleglise** [comment]
This DHIS2 version 2.23-SNAPSHOT does not properly manage the new OSM policy.
