### ISSUE TITLE
Remove surnumerical categories

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#119]
Following action items of the Meeting notes 20160626, could you please also remove surnumerical categories?

**Comment by arunimam** [comment]
Kindly explain with an example?

**Comment by Aleglise** [comment]
Agro - processing is an example of category to remove.

See http://dhis2.github.io/dhis2-docs/2.23/en/user/html/dhis2_user_manual_en_full.html#d0e675

**Comment by arunimam** [comment]
These categories cannot be removed from UI

You can ask Abyot to remove these extra categories from backend

**Comment by arunimam** [comment]
These categories cannot be removed from UI

You can ask Abyot to remove these extra categories from backend

**Comment by abyot** [comment]
I can help you with the removing if I get the list of attributes that needs to be removed.

**Comment by Aleglise** [comment]
All data element group and indicators groups which have -to be deleted in their name.

All categories and corresponding categories options except Baseline&TargetandProgress, Budget source, Budget type, Stakeholders 20160630

At least a good solution is to unmarked it as dimension to not let the users see them in pivot table...

**Comment by abyot** [comment]
I can remove the mentioned items.

Do you want me to remove those data elements and indicators assigned for the to be deleted groups?

Also, if there is some meta-data change that needs to be done, I prefer somebody else to do it. For example, if you want to keep the items to be there but marked as non dimension then I won't do that.

**Comment by Aleglise** [comment]
Categories were moduified with data dimension property to false.
![image](https://cloud.githubusercontent.com/assets/8737709/18580153/23804f54-7bfa-11e6-9b8b-8b1a5b421503.png)
