### ISSUE TITLE
How to select data element in GIS ?

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#120]
Accessing to GIS, how to select a data element ? In Data eleemnt group, [All Data Element] option is not available whereas it is in data visualizer and pivot table.

![image](https://cloud.githubusercontent.com/assets/8737709/17399484/8839f32a-5a42-11e6-9f76-9c7d16dc991d.png)

**Comment by abyot** [comment]
This is a minor limitation we have. Currently, the only way is to use data element / indicator group.

**Comment by Aleglise** [comment]
So, how to select data elements in maps ? Shal we create a new data element group which may be called [all data element] to let user create maps with data elements ?

**Comment by abyot** [comment]
Yes, we just have to create data element and indicator groups. this way we will be able to select.
