### ISSUE TITLE
Unapproved data are reported at province level whereas it should not 

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#121]
According to http://dhis2.github.io/dhis2-docs/2.23/en/user/html/dhis2_user_manual_en_full.html#d0e9041: 
"If the option Hide unapproved data in analytics is enabled, data will be hidden from viewing by users associated with higher levels."

Even if the option is checked:
![image](https://cloud.githubusercontent.com/assets/8737709/17434489/f6d31582-5b0a-11e6-98ce-8caa302fb6c0.png)

Unapproved data entered: 

![image](https://cloud.githubusercontent.com/assets/8737709/17434584/9001db6c-5b0b-11e6-96e7-d6df195f3dcb.png)

Unapproved data at district level is visible at district level (OK):
![image](https://cloud.githubusercontent.com/assets/8737709/17434600/a403aae6-5b0b-11e6-8244-667dcd08108b.png)
![image](https://cloud.githubusercontent.com/assets/8737709/17434628/c65e9402-5b0b-11e6-980e-a1cc3ff8cbba.png)

Unapproved data is visible at province level (higher level) (**KO**):
![image](https://cloud.githubusercontent.com/assets/8737709/17434660/f5517ffe-5b0b-11e6-93fe-a1caea506d8c.png)

**Comment by abyot** [comment]
I am not sure if this is a bug. . If you see the whole paragraph of the documentation, 

_**"If the option Hide unapproved data in analytics is enabled, data will be hidden from viewing by users associated with higher levels. When determining whether a data record should be hidden for a specific user, the system associates a user with a specific approval level and compares it to the level to which the data record has been approved up to. A user is associated with the approval level which matches the level of the organisation unit(s) she is linked to, or if no approvel level exists at that level, the next approval level linked to an organisation unit level below herself. A user will be allowed to see data which has been approved up to the level immediately below her associated approval level. The rationale behind this is that a user must be ablet to view the data that has been approved below so that she can eventually view and approve it herself.

Note that if the user has been granted the View unapproved data or the ALL authority she will be able to view data irrespective of the approval status."**_

Are you sure this does not apply to the user you checked with?

Also, can someone explain me the approval workflows? What is the difference between these approval workflows?

District Approval for Sector Quarterly Datasets
National Approval for National Quarterly Datasets
National Approval for Province Quarterly Datasets
Province Approval for District Quarterly Datasets

**Comment by Aleglise** [comment]
The user that we used does not have View unapproved data authority.

@abyot : @arunimam set the workflows and will provide information about it but the name of workflow suggests that according to the level of collection and the frequency, different workflows apply.

**Comment by arunimam** [comment]
District Approval for Sector Quarterly Datasets : In this workflow the approver is District authority and it approves the data for sector level datasets
National Approval for National Quarterly Datasets: In this workflow the approver is National authority and it approves the data for national level datasets
National Approval for Province Quarterly Datasets:In this workflow the approver is National authority and it approves the data for province level datasets
Province Approval for District Quarterly Datasets:In this workflow the approver is Provincial authority and it approves the data for district level datasets

**Comment by Aleglise** [comment]
@arunimam : actually the problem is that, with current approving workflows, it is not possible to report approved data after approving. Only users with View unapproved data authority can see the approved data.
So, it suggest that, with the current approval settings, data is not approved after approval.

Could you please update approval settings to let users without View unapproved data authority be able to report approved data? Thank you.

**Comment by Aleglise** [comment]
@arunimam : there is a problem with approval workflow settings. Please update how to visualize approved data without View unapproved data authority.

**Comment by Aleglise** [comment]
On demo instance user Usertest02 (pwd=Just4you) which does not have View unapproved data authority cannot report any data (example 11 favorite) whereas lot of data were entered and approved:
![image](https://cloud.githubusercontent.com/assets/8737709/17540244/ef85e996-5eb4-11e6-989f-a9dbecf2b162.png)

@abyot can it be realted to some of the development done?

@arunimam please provide a whole data entry entry, approval and reporting with a user without  View unapproved data authority

**Comment by arunimam** [comment]
Please confirm Do you want me to create a user with roles : data entry,approval without View unapproved data?

**Comment by Aleglise** [comment]
@arunimam . I want you to create a set of userswe need a working approving process withb real users to play the follow scenario. 

1/One data entry officer enters data
2/One approving data officer approves data
3/Data is available in pivot table without View unapproved data

For further information, please check the specifications and ask @abyot . I am on leave. Thank you in advance for your expertise.

**Comment by arunimam** [comment]
@abyot

Can you please explain - 

a) how many users we need to create?
b) each scenario mentioned above will have its own user - data entry officer and data approval officer?
c) what is this View unapproved data?

**Comment by Aleglise** [comment]
@arunimam 

We need you to create 2 users roles:
Role 1: data entry officer 
Role 2: approving data officer

This 2 roles should allow to enter data (role 1) and to approve data (role 2).

The data approving scenario will use one user with role 1 and one user with role 2. At the end of the scenario it should be possible to report approved data in reporting modules (GIS, pivot, etc) without View unapproved data authority.

View unapproved data is a standard DHIS2 authority (see http://dhis2.github.io/dhis2-docs/2.23/en/user/html/dhis2_user_manual_en_full.html)

**Comment by Aleglise** [comment]
This issue just raised that the approving process is not properly defined.
I am asking you to set a working approving process. It should be done before Friday.

**Comment by arunimam** [comment]
@Aleglise 
The user roles you are talking about are already created in DHIS2- Data Enty & Data Approval
Now I have unassigned the authority of View unapproved data from Data approval role

@abyot 

I created two users : Test_data_entry_officer & Test_data_approval_officer: password is Test@12345, same for both the users. 
I entered data from user Test_data_entry_officer in dataset: B001IPPA Vision 2020 and EDPRS-2 targets for economic growth and poverty reduction supported by agriculture sector Province Level Annual Dataset in the year 2016 in orgunit East for Minagri stakeholder

![image](https://cloud.githubusercontent.com/assets/12066960/18138368/f8890a52-6fc9-11e6-940d-405f7cda3a09.png)

Then i logged in from Test_data_approval_officer to approve the data, but the data entered in the same period is not visible there to approve though Approve button is highlighted and approval status is Approve: 1 items but why the data is not visible. 

![image](https://cloud.githubusercontent.com/assets/12066960/18138497/81f63f80-6fca-11e6-8e2a-d63d8e61ac24.png)

**Comment by arunimam** [comment]
Requesting Abyot to please check this issue because as per our previous discussion on Data Approval process last 2-3 months back , it was found out that the work flows created were wrong then we rectified the workflows and thereafter the approval process was working fine. But as per Alex's mail we are still at the same point with non working data approval functionality. 

@abyot I request you to please check the configuration of Data approval settings once more so that if still there is an issue we can rectify on time

**Comment by arunimam** [comment]
Also now i have unassigned the authority of View unapproved data from the user role Data approval and also unchecked the Hide unapproved data in Analytics but still the data entered is visible in pivot table

Please confirm if I am following the right steps or something is wrong

![image](https://cloud.githubusercontent.com/assets/12066960/18139388/e57695f6-6fce-11e6-8fbd-c18a19f7a41e.png)

**Comment by Aleglise** [comment]
@arunimam Please do not modify current user roles but create new ones.

**Comment by Aleglise** [comment]
@arunimam Also do not enter data in dev instance. Abyot cleaned this instance before delivery to customer. For test please use demo http://62.210.124.144:9090/demo

**Comment by Aleglise** [comment]
@arunimam I agree, our previous discussion on Data Approval process last 2-3 months back , it was found out that the work flows created were wrong then we rectified the workflows and thereafter the approval process was working fine. 

The probem is that it was working fine only if user used to report data had View unapproved data authority. **What we need is to have users without View unapproved data who can see in reporting modules only approved data.** 

We need you to create 2 users roles:
Role 1: data entry officer 
Role 2: approving data officer

This 2 roles should allow to enter data (role 1) and to approve data (role 2).

The data approving scenario will use one user with role 1 and one user with role 2. At the end of the scenario, it should be possible to report approved data in reporting modules (GIS, pivot, etc) with user Usertest02 (password: Test@12345) which don't have the View unapproved data authority.

**Comment by arunimam** [comment]
@Aleglise 
I will delete the data which i have entered and will do the testing in another instance
Also i will create two users (a) one for data entry (b) for data approval without View approving data authority

**Comment by arunimam** [comment]
@Aleglise 

I have created two users 
1) Test_data_entry_officer : Test@12345 for data entry
2) Test_approval_data_officer : Test@12345 for data approval without view unapproved data authority

Can you please create a user for me for demo instance so that i can do the testing?

**Comment by Aleglise** [comment]
@arunimam  &Neha Following last friday call, you have the credentials on demo.

Thank you for your update.

**Comment by Neha** [comment]
Wrong Neha :(

On Thu, Sep 8, 2016 at 11:27 AM, Alexandre Léglise <notifications@github.com

**Comment by Aleglise** [comment]
Please find a link to a document which describe the approval issue:
https://docs.google.com/document/d/1CLZgquPuZhH7mv11XIXFeiSIQW7WXn7Thra2HKlil0A/edit#

and a screencast which ilustrate what is described in the document:
https://drive.google.com/a/biosamples.co/file/d/0B9-HiXpk5KKkeFFRVTFyZFByS0k/view?usp=sharing.

Waiting to hear from you to set the meeting time to discuss about this issue.

**Comment by Aleglise** [comment]
Approval process allows to lock data. The approval process does not have effect on data visibility in reporting modules.
![selection_2016091610 37 45](https://cloud.githubusercontent.com/assets/8737709/18580071/af88b5e6-7bf9-11e6-9459-9d2f475e3789.png)
