### ISSUE TITLE
upgrading to 2.24

### ISSUE THREAD

**Issue by abyot** [minagri-rwanda/DHIS2-Agriculture#124]
with upgrade to 2.24, there are lots of features that MINAGRI can benefit. I am in the process of doing this. However, there are two areas where I would like HISP India team to help. Can we have all those developments by HISP India  (active users list and file value types for attributes) be merged with 2.24 code base?

**Comment by Aleglise** [comment]
@arunimam please take the lead on that and reply to @abyot 
Thank you

**Comment by Aleglise** [comment]
As developments by HISP India wasnt updated, DHIS2 upgrade was not done.
