### ISSUE TITLE
Replicate user fail

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#13]
Using Alex user, I am not able to replicate user whereas I should. When clicking on "Replicate" button, nothing happens and no user is created.
Alex user as superuser role which as ALL authority.

![infobulle_2016040612 06 06](https://cloud.githubusercontent.com/assets/8737709/14313313/266c30d6-fbf1-11e5-9178-2c336b1ff3ec.png)

**Comment by Aleglise** [comment]
If it helps, find below log associated to user replication:

> jquery.min.js?_rev=22003:2 POST http://62.210.124.144:9091/dev/api/users/djbQAwwLaY2/replica 500 (Erreur Interne de Servlet)send @ jquery.min.js?_rev=22003:2p.extend.ajax @ jquery.min.js?_rev=22003:2replicateUser @ user.js?_rev=22003:225onclick @ alluser.action:447
> VM3969:1 Uncaught SyntaxError: Unexpected token <$.ajax.error @ user.js?_rev=22003:235k @ jquery.min.js?_rev=22003:2l.fireWith @ jquery.min.js?_rev=22003:2y @ jquery.min.js?_rev=22003:2d @ jquery.min.js?_rev=22003:2

**Comment by abyot** [comment]
This is fixed now and sever is also updated.
