### ISSUE TITLE
Nothing to report in performance contract

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#14]
Why is there nothing to report in performance contract ?

![selection_2016040700 38 10](https://cloud.githubusercontent.com/assets/8737709/14335148/65d46a50-fc59-11e5-973d-587cc840b7a6.png)

**Comment by abyot** [comment]
There are meta-data changes and that needs to be reflected on the app. Right now I am focused on the results framework app.

**Comment by abyot** [comment]
First cut of the app is ready. Please pay special attention to meta-data configuration. A good example to follow is data set "9_TEST3-Baseline", its data element and assigned category options, category and category combination.

Since performance contract reports are generated on a yearly basis, those data set that appear for reporting in this app need to have either yearly or lower frequency.

![image](https://cloud.githubusercontent.com/assets/4967749/14763722/5872a21c-099e-11e6-80cf-c9282b1edac5.png)

**Comment by Aleglise** [comment]
In Rwamagana District, I entered Baseline, target and progress for 2015. Then, I ran analytics but nothing is displayed in Performance contract.

**Comment by abyot** [comment]
It could be a cache issue ... I am getting this

![image](https://cloud.githubusercontent.com/assets/4967749/14789178/9f4310a0-0b0b-11e6-8433-522c44ebc218.png)

**Comment by Aleglise** [comment]
I got the same result with cache clearing.

However. performing data entry on Nyagatare District for year 2014 and performing analytics, I face the same issue:
![image](https://cloud.githubusercontent.com/assets/8737709/14789927/2db59936-0b0f-11e6-8d91-d03089c4ecc8.png)

It will be limitated if user have to clear cache to see Performance contract.

**Comment by abyot** [comment]
No, you do not have to clear your cache now and then.

For example I haven't cleared my cache... but here is what I got.

![image](https://cloud.githubusercontent.com/assets/4967749/14790001/8c5e2070-0b0f-11e6-8514-30d2107ebb69.png)

**Comment by Aleglise** [comment]
I log in with "admin" user and do not see data:

![image](https://cloud.githubusercontent.com/assets/8737709/14790096/09ae988e-0b10-11e6-997f-f3fe1eb54bfb.png)

**Comment by abyot** [comment]
Are you still not able to see data?

**Comment by Aleglise** [comment]
I can now see data for 2014.
But after data entry for 2011,  data analytics and log out, I am still not able to visualize the entered data:
![image](https://cloud.githubusercontent.com/assets/8737709/14951408/f9ff999e-1058-11e6-87b7-672a025819b7.png)

**Comment by abyot** [comment]
I can see data for 2011. I haven't done anything - just went to performance contract made the selections to orgunit, indicator group and period. Below is what I got.

Will it be possible for you to record the exact steps you have taken? While doing this can you open chrome's dev console and watch for any error logs?

![image](https://cloud.githubusercontent.com/assets/4967749/14951491/98a9e4e6-1059-11e6-9ff8-5a25dc1ddc5c.png)

**Comment by Aleglise** [comment]
PLease find the steps here:

https://drive.google.com/a/biosamples.co/file/d/0B9-HiXpk5KKkcjdmWmpYVjJOdTg/view?usp=sharing

**Comment by abyot** [comment]
Hi,

In this link you sent, I haven't seen you running the analytics.

**Comment by Aleglise** [comment]
Running Analytics I can see data entered for 2013 and there is no error in console during the process.
But still nothing for 2011... Am I missing something else ?
![image](https://cloud.githubusercontent.com/assets/8737709/14954970/bd7c3c98-1076-11e6-8ad9-afda1608e213.png)

**Comment by abyot** [comment]
I am closing this again. The normal operation is that:
1. enter data 
2. run analytics
3. go to performance contract app and generate reports

There is no need to logout and login again. 

One scenario I can think of is: if you have run the same report multiple times - before the analytics is run - and was getting empty report. The next time you access the same report (this time after running the analytics) you could be getting empty report. This is mostly an issue with both the server and client doing caching. A solution for this - if you are sure that you have entered data, have run analytics and still getting empty data - is to try refreshing your browser or clear browser cache.

**Comment by Aleglise** [comment]
OK. I probably faced the issue linked with cache management.
