### ISSUE TITLE
Project modification fail

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#15]
When creating a project and editing project name, modifications are not saved.
(See https://drive.google.com/open?id=0B9-HiXpk5KKkQTQxSWNDQlJCXzg)

**Comment by abyot** [comment]
Not able to reproduce this. It could be a cache issue,

**Comment by Aleglise** [comment]
After cache clearing, I am able to reproduce this issue.

Just after creation, it is not possible to edit project (ex. Status).

**Comment by Aleglise** [comment]
Console log

> angular.js:87 PUT http://62.210.124.144:9091/dev/api/projects/undefined 404 (Not Found)

**Comment by Aleglise** [comment]
...and accessing again to the project "extension possible" is reset to empty whereas previous valus was yes (ex. project_TEST_18).
![image](https://cloud.githubusercontent.com/assets/8737709/14381002/455ea346-fd83-11e5-996b-0448c976477d.png)
