### ISSUE TITLE
Display more projects attributes

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#20]
In http://62.210.124.144:9091/dev/dhis-web-results-framework/index.html#/project & http://62.210.124.144:9091/dev/dhis-web-results-framework/index.html#/program lists, it would be easier to display Created and Last updated attributes.

It is the case in others DHIS2 screens where there are numerous entries like dataElement, Indicator, screens

**Comment by abyot** [comment]
We can have that... for now I have added "lastUpdated". But the thing is we can't have all, at some point we need to decide which columns to show.

![image](https://cloud.githubusercontent.com/assets/4967749/14769839/30093eca-0a62-11e6-98ae-5172e510e8ab.png)
