### ISSUE TITLE
Every user access to Active Users List

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#21]
User Demo_Data_Entry can access to Active Users List whereas this menu should be available for users with authority only.

![image](https://cloud.githubusercontent.com/assets/8737709/14605291/449db4c2-0578-11e6-8f4f-801d18e64770.png)

**Comment by mithileshhisp** [comment]
Dear Alex,
                In side Active User list we show 4 columns like name, username, active since and expire now. The expire now  column only be available for user which has a role like "F_ACTIVE_USER_EXPIRE" using this authority the user can Expire the session of that user which are logged in from long time and no any activity done by him/her and active user list available for all users
