### ISSUE TITLE
Sorting attributes does not work

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#22]
On http://62.210.124.144:9091/dev/dhis-web-results-framework/index.html#/ clicking on results framework attributes (ex. status) does not lead to sorting according to the clicked attribute whereas it should sort the displayed value.

![infobulle_2016041912 21 49](https://cloud.githubusercontent.com/assets/8737709/14636059/a1ba53ac-0629-11e6-9bb2-2e5cab6fd699.png)

**Comment by abyot** [comment]
we do not have sorting yet... what we have is paging and searching, currently this one is only for Projects

**Comment by Aleglise** [comment]
OK. So, please disable cursor change on field to not let userthink that there is an action here.

**Comment by abyot** [comment]
Sorting is now possible.
