### ISSUE TITLE
How to assign data set to project?

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#23]
In http://62.210.124.144:9091/dev instance I've created 3 data elements
9 Project TEST Execution Program 1.1
9 Project TEST Execution Program 1.2
9 Project TEST Forecast

I also created 2 datasets
9 TEST Project Forecast
9 TEST Project Execution
for each, relevent data elements are linked, type is specified and districts assignment is done

When editing 9 Project TEST ab project, why these datasets are not available for assignement?

**Comment by abyot** [comment]
It is because you do not have access to these data sets - check this under userroles. Also keep in mid that, every time you make changes to meta-data (those metadata that we create using the standard DHIS2 menu) - you need to clear cache.

**Comment by Aleglise** [comment]
I created "9 Project TEST ab" user role with 2 datasets
9 TEST Project Forecast
9 TEST Project Execution

I assign this role to Alex user

Actually it works now but only after log out and log in. Is this log out and log in action always a mandatory step ? If yes, I will add it as comment to the project functionnalities list.

**Comment by abyot** [comment]
You do not need to log-out and log-in. If you can write down the exact steps to reproduce, I can try to fix.

**Comment by Aleglise** [comment]
Yes. no need to log-out and log-in. it works fine.
