### ISSUE TITLE
Heterogenic sub-programs display

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#24]
Sub-programs sorting is different in program screen and in contribution to results framework pop-up whereas it should be the same to offer homogenic subprogram display.

In program screen:
![image](https://cloud.githubusercontent.com/assets/8737709/14638332/350bb936-0637-11e6-936d-e7e22188eeb8.png)

In contribution to results framework pop-up:
![Uploading image.png…]()

**Comment by abyot** [comment]
Fixed and server updated.
