### ISSUE TITLE
User image update

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#25]
Would it be possible to set a black user  or neutral instead of a white one ?
![infobulle_2016042010 06 05](https://cloud.githubusercontent.com/assets/8737709/14667462/b7df0ba8-06df-11e6-8669-0f817ed4844f.png)

**Comment by abyot** [comment]
I do not see white, rather  orangeish ... :) anyways that is the standard icon we have. bring an icon / image and we can use that.

**Comment by Aleglise** [comment]
:)
Please use http://iconmonstr.com/user-5/

It will be homogenic wore with Active users list.

**Comment by Aleglise** [comment]
Updating account icon will be enought. We can leave help as it is.

**Comment by abyot** [comment]
Fixed. 
![image](https://cloud.githubusercontent.com/assets/4967749/14761620/d0eb6cd4-0966-11e6-973a-b2bcde300b72.png)
