### ISSUE TITLE
Resize Contribution to results framework

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#26]
Result program have dozen of sub-program. Consequently the Contribution to results framework pop up will be very long.

Reducing checkbox size (and table cell up & down margins) will allow to reduce pop up height.

![image](https://cloud.githubusercontent.com/assets/8737709/14667965/1e375f7a-06e2-11e6-9800-00b270cbb6aa.png)

**Comment by abyot** [comment]
sure, may be better is to add scroll-bars

**Comment by Aleglise** [comment]
I do not talk about scroll bar which is already available but just to reduce height and therefore reduce scrolling...

**Comment by abyot** [comment]
I am talking about scroll-bar for the popup - not for the page. Reducing check-box size is not a proper solution. Unless we have a scroll-bar, we will end-up with the same problem when we face lots of sub-programs.

**Comment by abyot** [comment]
Fixed. 

![image](https://cloud.githubusercontent.com/assets/4967749/14765772/4e9f2e4c-09f1-11e6-9260-43c346781bf4.png)
