### ISSUE TITLE
Active users list menu entry not available

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#27]
Active users ist not available for user TEST_bot. TEST_bot is a replicate of Alex user.

![infobulle_2016042011 35 16](https://cloud.githubusercontent.com/assets/8737709/14670343/027d57b6-06ed-11e6-84e4-e7dee94a579f.png)

**Comment by abyot** [comment]
This is from Mithilesh / HISP India. Could you please assign it to them.

**Comment by mithileshhisp** [comment]
for resolved this issue we have to update the file name "maintenance.js" and location is 
war-file\dhis-web-maintenance\maintenance.js

[maintenance.zip](https://github.com/minagri-rwanda/DHIS2-Agriculture/files/231710/maintenance.zip)

**Comment by Aleglise** [comment]
@arunimam we didn't discuss about this issue during call. It would like to have it ready for restest this week.

**Comment by Aleglise** [comment]
As the issue doesn't move, I changed assignee.

**Comment by abyot** [comment]
Should be fixed by now.
