### ISSUE TITLE
Change category combo assigned to a data element

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#29]
When a category combo was assigned to a data element and when data entry was performed for this data element, is it possible to update the category combo ?

Ex. a data element is gender disaggregated and after 2 years, users want to add a new dissagregation (ex. member of a cooperative or not ) or to remove gender disaggregation.

I saw that Edit DataElement Category Combo is a trigger for new data set version but does it allow to still have the full tracability and to report the data element across "different category combo periods"?

**Comment by abyot** [comment]
No. Once data is collected for a given category combination, it is not possible to change the category combination in anyway. The problem is - what do we do with the previously collected data? The solution is to create another category / category combination. It is possible to use category options.

**Comment by Aleglise** [comment]
Ok. So you mean that creating a category / category combination is a solution. 
In this case, can the newly created category / category combination be assigned to the same dataelement?

**Comment by abyot** [comment]
Yes creating a new category combination is the solution. Actually you would have to create a new data element as well. The thing is - again what do we do with the previously collected data? 

It is not possible to change the meaning of a data element or category combo across time/period. We can change value across period but not meta-data.

We can't say data element A was about "Farmers of category X, Y , Z" and a year latter it becomes about "Teachers of category A, B, C".

**Comment by Aleglise** [comment]
Ok. The example was to track 
Agriculture households with permanent kitchen gardens disaggregated by gender

and to update it to 
Agriculture households with permanent kitchen gardens disaggregated by memberhip of a cooperative

in this example, you can see that the data element is the same (Agriculture households with permanent kitchen gardens). It is only that disaggregation which is different.

So, you confirm that for this example we have to create a new data element (and therefore loose tracability) if we want to change the disaggregation criteria?

**Comment by abyot** [comment]
Yes, unfortunately. 

By the way if you really look into it - "Agriculture households with permanent kitchen gardens disaggregated by memberhip of a cooperative" and "Agriculture households with permanent kitchen gardens" are two different meta-data.

**Comment by Aleglise** [comment]
Ok. Thanks.
