### ISSUE TITLE
Which datasets to assign to a sub program ?

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#3]
Wen creating a new RF, how can we know which dataset to assign to a sub program ?

Abyot: One thing I have in mind is to modify the new property we have here http://62.210.124.144:9091/dev/dhis-web-maintenance-dataadmin/showUpdateAttributeForm.action?id=3337

**Comment by Aleglise** [comment]
@abyot : OK. What will be the consequences of the modification ?

**Comment by Aleglise** [comment]
test comment update slack

**Comment by abyot** [comment]
@Aleglise the consequence is of course some extra work. We anyways have to do it, otherwise there is no way for us to control data entry for impacts, outcomes and outputs. One key requirement to link data set with results framework (including sub-program) is that data can only be entered so long as we have an active results framework. 

If data sets are not linked to results framework, data can be entered periodically and indefinitely.

**Comment by Aleglise** [comment]
Ok. My question was about the consequence in term of business rules and specifically to know which dataset to assign to a sub program.

**Comment by abyot** [comment]
Ok, now I see what you mean. The user needs to know what he/she is doing to some extent. It is like asking - which data element does a user assign to a data set.

One line of thinking is that - we know which indicators a sub-program contains, this then means knowing  which data elements belong to these known indicators ... then knowing to which data set these data elements belong.

At one point I was telling the HISP India team to use some naming convention when creating meta-data. My suggestion when creating a data set was to use the same name as the sub-program. In ideal scenario, we will have one data set per sub-program. However, we might end-up having with multiple data sets per sub-program. This can happen if indicators/data elements that belong to a single sub-program are collected at different  frequency and/or orgunit level. When this happens, my advise for them was to again give the data set the same name as the sub-program but append level or frequency information at the end. If such convention is followed strictly, then we will have little problem in identifying to which sub-program a data set belongs.

**Comment by Aleglise** [comment]
So, this issue should be assigned to Arunima

**Comment by arunimam** [comment]
discussed and agreed
