### ISSUE TITLE
Redundant sector names

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#31]
Some sectors have the same name ex Murundi which exists under Kayonza & Karongi districts

![selection_2016042511 30 42](https://cloud.githubusercontent.com/assets/8737709/14779688/989fc5c2-0ad9-11e6-9253-676e08602327.png)

![selection_2016042511 29 42](https://cloud.githubusercontent.com/assets/8737709/14779685/943dc0ba-0ad9-11e6-8ab9-d919fb034d5a.png)

Why one sector have the parent district recalled in the sector's name and the other not ?
It would be better to have a systematic rule in sector naming and to systematicaly recall district name if several sector have the same name.

**Comment by abyot** [comment]
This is meta-data - something which we can remove/add/edit. If what is there is not what we want - we can simply delete and create what fits best the MINAGRI structure.

**Comment by Aleglise** [comment]
OK.
