### ISSUE TITLE
Rename Results Framework App

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#32]
Results Framework
instead of 
Result Framework

![image](https://cloud.githubusercontent.com/assets/8737709/14788225/505800e4-0b07-11e6-9c6f-801111ca391d.png)

**Comment by abyot** [comment]
Is this really important? Because, I removed the 's' so that the label stays in one line. Otherwise it will overflow to a new line.

**Comment by Aleglise** [comment]
This is a low resolution issue. But for customer, there is only Results Framework.

**Comment by abyot** [comment]
Fixed.
