### ISSUE TITLE
Wrong data set periodicity

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#33]
When selecting a baseline data set  (9_TEST3-Baseline) and then selecting a target data set (9_TEST3-Target), the target data set periodicity is annual whereas it should be quarterly:
![selection_2016042517 23 48](https://cloud.githubusercontent.com/assets/8737709/14789210/c3e63432-0b0b-11e6-86d1-d26d1a84863c.png)

Then selecting a target data set and switching to baseline, it is possible to enter quarterly data for Baseline:
![image](https://cloud.githubusercontent.com/assets/8737709/14789163/8a4fb13a-0b0b-11e6-892e-c787de3f00f3.png)

**Comment by abyot** [comment]
Yes, I am aware of this and working on a fix. If you refresh, it works.

**Comment by abyot** [comment]
Fixed. You need to clear your cache to retest.
