### ISSUE TITLE
Progress-Soil Conservation and Land Husbandry District Level Quarterly Dataset has yearly periodicity

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#34]
Why Progress-Soil Conservation and Land Husbandry District Level Quarterly Dataset has yearly periodicity ?

**Comment by Aleglise** [comment]
Same issue for Target-Soil Conservation and Land Husbandry District Level Quarterly Dataset and Baseline-Soil Conservation & Land Husbandry District Level Quarterly Dataset

**Comment by arunimam** [comment]
the periodicity of Progress & Target-Soil Conservation & Land Husbandry District Level Quarterly Dataset has been changed to Quarterly now.
For the Baseline-Soil Conservation & Land Husbandry District Level Quarterly Dataset the periodicity is yearly as the baseline data is yearly data

**Comment by Aleglise** [comment]
Ok for baseline yearly periodicity.
The periodicity of Progress & Target-Soil Conservation & Land Husbandry District Level Quarterly is still yearly:
![image](https://cloud.githubusercontent.com/assets/8737709/14978202/6e83ddc2-111a-11e6-94bc-fb1189b5ad06.png)

It seems that the retest is only KO for Progress & Target-Soil Conservation & Land Husbandry District Level Quarterly but OK for Progress and Target-Soil Conservation & Land Husbandry District Level Quarterly. I think that you created these duplication to test gender dissagregation (using category or not). To be clear and homogenic please update Progress & Target-Soil Conservation & Land Husbandry District Level Quarterly periodicity and rename datasets to clearly show which are using categories or not.

**Comment by arunimam** [comment]
The periodicity have been changed now

Yes you are right, there are two types of datasets :
      ---one type is with the data elements assigned the category combination of Gender               household,Baseline,Target&Progress
      ---second type is with the gender based data elements (male & female) & assigned with the category combination of Baseline,Target&Progress

Now renamed the datasets: One with category combination have CC in their name & another 
with the gender based data elements have (M&F) in their name and the

**Comment by Aleglise** [comment]
Renaming is ok. It is clearer like that. 
Progress(M&F)/Soil Conservation & Land Husbandry District Level Quarterly Dataset is still yearly whereas it should be Quarterly

**Comment by arunimam** [comment]
Please check now. Periodicity changed to Quarterly
