### ISSUE TITLE
Arrow button in performance contract does not work

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#35]
On performance contract
![image](https://cloud.githubusercontent.com/assets/8737709/14951438/29b31364-1059-11e6-92e2-8289cc31d5ba.png)

Arrow button does not work as expected (when clicking on it we are expecting changing period)
![image](https://cloud.githubusercontent.com/assets/8737709/14951451/4a0e00ec-1059-11e6-951c-26c133ee9d22.png)

**Comment by abyot** [comment]
If you carefully look at the drop-down list - those before and after clicking the arrows are not the same. At least one year is added (when data set is baseline) to the list.

**Comment by Aleglise** [comment]
Sometime the arrow doesn't work:
https://drive.google.com/a/biosamples.co/file/d/0B9-HiXpk5KKkUmhOOGNaZkxZQ1k/view?usp=sharing

**Comment by abyot** [comment]
I think there is a misunderstanding on how the arrows are supposed to work. See the standard data entry to have an understanding of how the arrows are working.

The arrows are not meant to take you from one period to another, rather to generate list of periods in a given time line. Usually we display list of **valid** periods in a current year. But if you are interested to enter data for a period from last year, the period needs to be generated - the back arrow does that and populates the period drop-down. The forward arrow is used normally when you are in previous years (relative to current year) and want to enter data for latest periods.

With this assumption of the working of the arrows, I do not see any problem. Hence, no bug.
