### ISSUE TITLE
Stakeholder selection on data entry 

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#36]
When entering data why stakeholder (NAEB, RAB, etc.) is not display for selection as it was the case in the past?

**Comment by abyot** [comment]
I don't know why it worked before and not now. But this is purely a meta-data issue. 
- First make sure all stakeholders are registered as category options. 
- Then create a category of type **Attribute** using these category options. 
- Create a category combination of type **Attribute** using the above category
- Assign this category combination to your data set.

**Comment by arunimam** [comment]
We can make the necessary changes. 
Requesting you to kindly provide the list of stakeholders & list of dataset for which these changes needs to be done

**Comment by Aleglise** [comment]
I would say that a stakeholder sould be selected for every data entry and therefore every data set. I let Abyot confirm that, especialy regarding project data sets..
The list should be editable by DHIS2 admin but you can create RAB, NAEB, MINAGRI & SPIU for testing.

**Comment by Aleglise** [comment]
AS Abyot is not available now, let assume that stakeholder sould be selected for every data entry.

**Comment by arunimam** [comment]
Stakeholder list SPIU,MINAGRI,RAB,NAEB are now available for data entry in each dataset

Please check

**Comment by Aleglise** [comment]
May be added:
BNR
IAHS
NISR
RCA
