### ISSUE TITLE
Wrong information message when loading RF App

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#37]
When opening RF App, before to load the RF list, there are 2 information messages 
1/Loading meta data
2/No results framwork available
![image](https://cloud.githubusercontent.com/assets/8737709/14951578/3f9d0580-105a-11e6-93fe-6ec349776fd1.png)

When internet connection is slow the first message is displayed quickly then the 2nd message is displayed during few dozen of seconds.

So, this second information message should be displayed only if the is actually no data to display

**Comment by abyot** [comment]
Fixed.

**Comment by Aleglise** [comment]
retest OK.
