### ISSUE TITLE
Approving data from lower levels than District?

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#38]
After having performed data entry for Nyagatare District - Jan to Mar 2016 for Progress-Soil Conservation and Land Husbandry District Level Annual Dataset 
 I am not able with admin user to approve entered data. A message is displayed: waiting for lower level to approve whereas I sould be able to approve.

![image](https://cloud.githubusercontent.com/assets/8737709/14958685/276c84d6-108c-11e6-9cf6-3a2c97267604.png)

**Comment by arunimam** [comment]
Data is approved at one level higher. 
                        Facilities data is approved by Sector
                        Sector data is approved by District
                        District data is approved is Province
                        Province data is approved by National
Hence the district data needs to be approved by Province first. So requesting you to use the province username to approve the data

**Comment by Aleglise** [comment]
Thank you Arunima.
2 questions:
1/If data  is approved at one level higher why the foloowing message is displayed?

> Approval status : waiting for **lower** level to approve

2/ What do you call "the province username"?

**Comment by arunimam** [comment]
Does the admin user can approve data of any level?
Or else the approval has to go according to the level means only one level higher can approve the data?
If yes then do we need to create usernames for every level to approve data

**Comment by Aleglise** [comment]
As Abyot is not available, we have to progress on this issue without him for the moment.

Target workflow is the following:
- a clerk enters the data
- his/her superior approves/disapproves the data
- if disapproved, the data remains editable
- if approved, the data becomes read only and passes on to the above level for carry-on approval

Data can be entered at district, province or national level.

**Comment by arunimam** [comment]
As written earlier the data is approved as per the workflow from lower to higher level

Kindly use province user name : ProvinceApp Password: Pro@1234

**Comment by Aleglise** [comment]
To be able to access to the system, I updated Data Approval user role and added "See Dashboard integration module" autority to it.

**Comment by Aleglise** [comment]
After having performed data entry for Nyagatare District - Jan to Mar 2016 for Progress(CC)-Soil Conservation and Land Husbandry District Level Quarterly Dataset (for which "Half yearly Approval- for Half-yearly datasets (Quarterly)" Data approval workflow is selected)

With ProvinceApp user, I am able to see entered data but the message is now "Nothing to do":
![image](https://cloud.githubusercontent.com/assets/8737709/15203235/d1bcb11e-1801-11e6-8002-3fca8f9801f1.png)

**Comment by arunimam** [comment]
Kindly check now 

![image](https://cloud.githubusercontent.com/assets/12066960/15239831/294abc62-1903-11e6-9042-22f24959bd11.png)

**Comment by arunimam** [comment]
Check with ProvinceApp user name

**Comment by arunimam** [comment]
[Data Approval.docx](https://github.com/minagri-rwanda/DHIS2-Agriculture/files/262710/Data.Approval.docx)

Attach is the SOPs for Data Approval
