### ISSUE TITLE
DHIS2 system requirements

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#39]
What are system requirements for DHIS2 ? 
On which metrics should we based system requirements per instance (nb of users, volume of data, ...)? 

I didn't find information on https://www.dhis2.org...

**Comment by abyot** [comment]
Are you looking for something like this? 

http://dhis2.github.io/dhis2-docs/master/en/implementer/html/ch08.html

**Comment by Aleglise** [comment]
Yes ! Thank you.
I <3 DHIS2 documentation! ;)
