### ISSUE TITLE
How to link impacts and outcomes to datasets ?

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#4]
Abyot: I will extend the data model so that it becomes possible to link data set to results framework

**Comment by Aleglise** [comment]
Now a "Data sets" tab is displayed. But how can we know which Data sets are linked to Impacts and which Data sets are linked to Outcomes ?

![selection_2016040410 33 53](https://cloud.githubusercontent.com/assets/8737709/14242368/e6230e24-fa50-11e5-9700-9704b747043d.png)

**Comment by abyot** [comment]
In Data set management UI, it is possible to define data set type. Currently available types are - Impact, Outcome, Output, Budget forecast and Budget execution.
