### ISSUE TITLE
Performance Contract - After clearing period, the liste is empty whereas available periods should be displayed

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#40]
When clearing period criteria:
![selection_2016050409 16 28](https://cloud.githubusercontent.com/assets/8737709/15007441/434a78cc-11d9-11e6-8a5b-e8c85617d073.png)

Period list is empty:

![image](https://cloud.githubusercontent.com/assets/8737709/15007410/0e166116-11d9-11e6-93c3-e62c1272ecaf.png)
C- After

**Comment by abyot** [comment]
This is a bug and will be fixed. For now, hitting refresh button solves the problem.

**Comment by abyot** [comment]
Fixed.
