### ISSUE TITLE
Performance contract - Limited period selection 

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#41]
Even if data can be entered for 2016
![image](https://cloud.githubusercontent.com/assets/8737709/15007475/a40152a8-11d9-11e6-9a10-8d0710daa3de.png)

It is not possible to report data after 2011:
![image](https://cloud.githubusercontent.com/assets/8737709/15007466/9691f8ca-11d9-11e6-9da4-fa9cd7bdda11.png)

**Comment by abyot** [comment]
There is a limit on the amount of options displayed in the drop-down list. The arrow buttons are meant to generate next and previous periods.

**Comment by Aleglise** [comment]
OK.
