### ISSUE TITLE
Unable to access to DHIS2

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#42]
After cache clearing I access to the following URL:
http://62.210.124.144:9091/dev/api/system/tasks/ANALYTICSTABLE_UPDATE?lastId=CFbhair54pP

Does it mean that user connot connect during analytics?

See https://drive.google.com/a/biosamples.co/file/d/0B9-HiXpk5KKkQm9UNjEwcjctREE/view?usp=sharing

**Comment by abyot** [comment]
This is not really entirely a DHIS2 issue - a mix of cache, browser... I would say, right after you cleared a cache - try to access the system from its base-url, in this case http://62.210.124.144:9091/dev/

On another note, accessing the system while the analytics is being run could potentially lead to unexpected behavior. This was the main reason for running analytics at mid-night when no one is entering data.

**Comment by Aleglise** [comment]
OK. I think that I faced some of these unexpected behavior... (issue #45 ?)
