### ISSUE TITLE
Project Budget forecast entry

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#43]
Till now we define in demo documents for budget forecast data element and data set to allow data entry of budget forcast.

Why is there another screen to enter budget forecast data ?
![image](https://cloud.githubusercontent.com/assets/8737709/15008280/74cab924-11df-11e6-9325-0822fd7c2324.png)

**Comment by abyot** [comment]
It is just convenient to do it this way. With the current approach, a user can finish everything about project from the same UI. It is also possible to access the same from data entry screen. What are your suggestions?

**Comment by Aleglise** [comment]
2 menus entries for the same data entry feature with no change in prequesites for project definition.

You do not have to select the data set.

If users are being confused, we will turn it off.

**Comment by Aleglise** [comment]
Let close it and wait for users feedback.
