### ISSUE TITLE
Authorities for Projects summary report 

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#44]
In specs §3.6.5 it is mentionned that View Global Projects Summary is allowed for Administrator and authorised users in relevant structures.

Is it possible to provide access to Projects summary report  without administrator role?

**Comment by abyot** [comment]
One does not need to have "Administrative role" to see projects. Anyone with access to projects app, will be able to see project summary. What exactly do we need?

**Comment by Aleglise** [comment]
Yes. We need to have users having authorities to access to Projects summary report only (without having access right to project edition.

**Comment by Aleglise** [comment]
Project / RF can be also splitted

**Comment by Aleglise** [comment]
defining authorities is OK

**Comment by Aleglise** [comment]
With authority "M_dhis-web-results-framework" user can see Projects summary report as RF and projects.
