### ISSUE TITLE
the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#45]
When creating a data element I have a message saying that "Object already exists" whereas the object doesn't exist.

in console I have the following error

> Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by abyot** [comment]
Are you still getting this?

**Comment by Aleglise** [comment]
No. Any idea about the source of this issue (which led to project creation impossibility)?

**Comment by abyot** [comment]
I am not able to reproduce this and closing...
