### ISSUE TITLE
Error message when data entry 

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#46]
When entering data for data set Baseline(M&F)/Soil Conservation & Land Husbandry District Level Quarterly Dataset, there is an error message saying that category combo does not exist:
![selection_2016050909 07 24](https://cloud.githubusercontent.com/assets/8737709/15105916/ea7eccd4-15c5-11e6-8309-909ed7881c17.png)

Then, a second error message is displayed 

![image](https://cloud.githubusercontent.com/assets/8737709/15105880/9a428de6-15c5-11e6-9cc1-97621c260baf.png)

Console

> form.js?_rev=22005:664 Loading form locally: YaOtJoh4u5a
> form.js?_rev=22005:2618 Successfully stored data value
> http://62.210.124.144:9091/dev/api/dataValues Failed to load resource: the server responded with a status of 409 (Conflict)

**Comment by Aleglise** [comment]
@arunimam As Abyot is not available, could you please have a look to this issue?

**Comment by abyot** [comment]
The message is pretty obvious. It means category options are either added/removed once a category combination is created. The solution is to delete your category combination and recreate as new.

**Comment by arunimam** [comment]
I have entered the data in same dataset Baseline(M/F) Soil Conservation & land Husbandry District Level Quarterly Dataset, but I didn't get any issue like this. Kindly check again

![image](https://cloud.githubusercontent.com/assets/12066960/15282341/4b428a16-1b60-11e6-9d7f-babe2e3c4608.png)
