### ISSUE TITLE
Users feedback about gender disaggregation

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#47]
We got feedback from users:
Users feedback about gender disaggregation:

> Gender have been assigned  to each indicator, it will be better to have the a column of total then female and men column ( but not mandatory) to allow some indicators that are not depending to gender sensitivity,

1/ Please review my reply to client about this feedback (I think that is is not possible to enter total without entery gender detail but please correct if I am wrong):
"According to Indicator files, gender isn't assigned to every indicator (ex. Indicator 4.6.1.3 Area under certified organic production schemes).
When the indicator is gender disaggregated, data entry should be done per gender. So, it is not possible to enter a total if the indicator is gender disaggregated."
To be able to enter total only, the indicator do not have to be gender disaggregated. Data should be homogenic.

2/ I will ask the question again about best option between CC or M&F for gender dissaggregation

**Comment by arunimam** [comment]
Male Female disaggregation is given to the indicators according to the Alina part 2 sheet , near about 30-35 indicators are gender disaggregated 
Requesting if you can provide the list of indicators in which you do not want the gender dissaggreagtion,we can remove that

**Comment by arunimam** [comment]
Also a dataset has been created Agricultural Environment Mainstreaming District Sector Level Quarterly Dataset for the indicators 4.6.1.2 & 4.6.1.3 and assigned at district and sector level. Both the indicators doesn't have gender disaggregation
