### ISSUE TITLE
Missing orgunits in DHIS2 app

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#48]
Using https://play.google.com/store/apps/details?id=org.dhis2.mobile&hl=en
whith demo URL and Alex user, some orgunits are not availbale for data entry:
![screenshot_20160509-101652](https://cloud.githubusercontent.com/assets/8737709/15107322/6f5f9d3a-15cf-11e6-8aa6-15dfba03c2ab.png)

Why?

**Comment by arunimam** [comment]
Android application is under refactoring. As of now it doesn't support the current system

**Comment by Aleglise** [comment]
Do you know when refactoring will be finished?

**Comment by arunimam** [comment]
team is trying to finish by end of june

**Comment by Aleglise** [comment]
ok great.
The project seems to be here : https://github.com/dhis2/dhis2-android-datacapture

**Comment by abyot** [comment]
This is not a bug, unfortunately the way the android apps work.

What the app does is that it shows top level assigned org units and their immediate children. If you go to user setting and make explicit assignment of orgunits then all will show up.

**Comment by Aleglise** [comment]
:)

![screenshot_20160526-103725](https://cloud.githubusercontent.com/assets/8737709/15568907/a154b0de-232e-11e6-8335-37b4d000f09c.png)

**Comment by abyot** [comment]
I am not sure I got your point ... but here is from my side

![image](https://cloud.githubusercontent.com/assets/4967749/15569071/95665ec0-232f-11e6-8d34-c202d6f65b53.png)

This is what I meant by explicit assignment of orgunits to user. The mobile looks like this

![screenshot_20160526-104731](https://cloud.githubusercontent.com/assets/4967749/15569111/ce47bcc0-232f-11e6-8f86-92c43ba298ea.png)

**Comment by Aleglise** [comment]
@abyot 
I closed this issue. So, it is solved. Thank you for your reply.

As you said, when assigning orgunit to users, it works.
