### ISSUE TITLE
Stakeholders list access rights

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#49]
How stakeholders list access rights can be managed ?

Typically, NAEB value will be available for NAEB users. These NAEB users do not have to be able to select RAB or SPIU.

**Comment by arunimam** [comment]
Stakeholders has been provided the access. Now NAEB cannot select and view Minagri data but the stakeholder needs to log in from his/her username & password

Username                        Password
Minagri                            Minagri@1234
NAEB                              Naeb@1234
RAB                                Rab@1234
SPIU                               Spiu@1234
