### ISSUE TITLE
Creating project fail

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#5]
When creating a project, Save button does not have any effect.

After trying to change status and Lead donor, I was able to create 
![selection_2016033115 47 30](https://cloud.githubusercontent.com/assets/8737709/14178176/cae8c6f2-f759-11e5-9bd4-eb6a3096289d.png)

but when accessing again to the menu entry, no project was available.
![selection_2016033115 48 22](https://cloud.githubusercontent.com/assets/8737709/14178184/d39d967e-f759-11e5-9ff0-b923ed454691.png)

**Comment by Aleglise** [comment]
Browser log:

[62.210.124.144-1459431938893.txt](https://github.com/minagri-rwanda/DHIS2-Agriculture/files/197772/62.210.124.144-1459431938893.txt)

**Comment by abyot** [comment]
Fix committed.

**Comment by Aleglise** [comment]
Retest KO. After creation, project is displayed but when accessing again to the menu, new project is not displayed anymore. see https://drive.google.com/open?id=0B9-HiXpk5KKkUGlWTjFOSFlVTnM

@abyot in future do not close issue but just assign to me for restest  when fixed. Thank you.

**Comment by Aleglise** [comment]
restest OK
