### ISSUE TITLE
Could you please share the current indicators list in dev instance?

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#51]

**Comment by arunimam** [comment]
http://62.210.124.144:9091/dev/api/indicators.json?fields=name,code&paging=false

**Comment by Aleglise** [comment]
Thank you.

 -Two indicators  doesn't have code : (Percentage of recommendations of Sector Agricultural Committee meetings accepted at district leand transmitted to the national level & Percentage of recommendations of Sector Agricultural Committee meetings integrated into crop husbandry practices)
- One indicator has a noncompliant format: 0.5  Annual value added from cropping and livestock keeping

Please correct them.

**Comment by arunimam** [comment]
Codes have been added in the two indicators mentioned above

Kindly clearly specify the second issue of non compliant format

**Comment by Aleglise** [comment]
indicator format code should satisfy a point separated 4 segments nomenclature (X.X.X.X) according to indicator group and indicator.

In Annex 2.2_Monitoring Framework_2015.12.18_part 2_(Alina), I do not see 0.5 code

**Comment by arunimam** [comment]
Kindly check whenever i update the code of the indicator Annual value added from cropping and livestock keeping, it keeps on showing validating. PFA the screen shot
![image](https://cloud.githubusercontent.com/assets/12066960/15350109/000eb4c0-1cf5-11e6-85c2-74bbb0d75f97.png)

**Comment by abyot** [comment]
Can you share your browse console log? If you are using chrome, go to Tools -> Developer Tools -> Console

**Comment by arunimam** [comment]
Pls check

![image](https://cloud.githubusercontent.com/assets/12066960/15359435/faa5168c-1d26-11e6-9338-022843d4a4ff.png)

**Comment by arunimam** [comment]
check this one-console

![image](https://cloud.githubusercontent.com/assets/12066960/15359570/954fd500-1d27-11e6-9ada-472f812a0297.png)

**Comment by abyot** [comment]
Seems there is a bug here.... the system is not handling duplicates. 

On another note, there is another indicator with the same code you are trying to enter. 

If you try the following

http://62.210.124.144:9091/dev/api/indicators.json?filter=code:eq:**0.0.1.4**

Go and modify the existing indicator or use a new code.

**Comment by arunimam** [comment]
Yes there was a duplicate Indicator, now deleted one indicator and updated the code 0.0.1.4 in Annual value added per rural household from cropping & livestock keeping
