### ISSUE TITLE
Approval Notification

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#52]
How approver is notified that he should approve data? How approver knows which data has to be approved?

**Comment by arunimam** [comment]
As per the norms in many countries and states in India there is a stipulated time for entering data. For e.g. the reporting period is 1st to 30th of a month , in this period the data entry person will enter data and between 1st and 5th of next month the approver/supervisor will approve/unapprove  the data. Hence its a process which every one follows
As such there is no functionality within DHIS but certainly we can use the Messages functionality for the notifications in which the data entry person can send a message to his/her supervisor/approver that the data has been entered and is ready for approval and similarly the approver can also send the message to that user
