### ISSUE TITLE
Data set naming convention

### ISSUE THREAD

**Issue by abyot** [minagri-rwanda/DHIS2-Agriculture#54]
Is it possible to use the following naming convention?

DATA_SET_NAME - Baseline
DATA_SET_NAME - Progress
DATA_SET_NAME - Target

This way we are sure that data sets of the same family are displayed together in sequence in data entry UI.

With the current approach of 

Baseline - DATA_SET_NAME
Progress - DATA_SET_NAME
Target - DATA_SET_NAME

Data sets are scattered here and there since the data entry module sorts data sets by name.

**Comment by arunimam** [comment]
Its ok we can change the dataset naming convention like the way you have suggested but one question is Does the data entry operator will not get any issue in searching which dataset is baseline, target or progress as the dataset name is lengthy and is not completely visible to the user

**Comment by abyot** [comment]
I am not sure if the problem you mentioned will be avoided by going suffix or prefix. I don't have a strong opinion, but my view is that going prefix is convenient.

**Comment by arunimam** [comment]
No issues 

So now should i go ahead with renaming of datasets?

**Comment by abyot** [comment]
have no strong opinion on this...

**Comment by arunimam** [comment]
We can ask Alex and moreover as of now we have three datasets with Baseline/Progress & Target

and lets wait for revert on the indicators whose periodicity & level is missing
