### ISSUE TITLE
Periodicity & Level Missing

### ISSUE THREAD

**Issue by arunimam** [minagri-rwanda/DHIS2-Agriculture#55]
Attached is the file where the indicators are mentioned for which either periodicity is missing or level is missing (checked in the Alina Part 1 & Part 2 sheet)

Requesting you if you can check these and provide the missing periodicity
[Periodicity & Level Missing.xlsx](https://github.com/minagri-rwanda/DHIS2-Agriculture/files/265775/Periodicity.Level.Missing.xlsx)
 & levels for these indicators so that datasets can be created for these indicators

**Comment by Aleglise** [comment]
To let us work easily on your request, could you please add indicator codes?

**Comment by Aleglise** [comment]
@arunimam please update this file asap

**Comment by arunimam** [comment]
Please check the sheet updated with indicator code
[Periodicity & Level Missing.xlsx](https://github.com/minagri-rwanda/DHIS2-Agriculture/files/269771/Periodicity.Level.Missing.xlsx)

**Comment by Aleglise** [comment]
Thanks. File sent to client.

**Comment by Aleglise** [comment]
Reply from client:

Please note that I added client's comments in the file.

[250516_Periodicity_Level_Missing.xlsx](https://github.com/minagri-rwanda/DHIS2-Agriculture/files/282209/250516_Periodicity_Level_Missing.xlsx)

**Comment by arunimam** [comment]
Thanks we will look into it and create the rest datasets

**Comment by arunimam** [comment]
1. There are 39 indicators whose periodicity is Quarterly & Annual both, its not possible to assign two periodicity to one indicator, we have to keep either of these
   2.There are 53 indicators whose level is mentioned as At least District (better Sector). What does it mean? 

Kindly confirm on these two points

**Comment by Aleglise** [comment]
@arunimam for indicators which are " At least District (better Sector)" level will be district for now. We are waiting for MINAGRI feedback about periodicity.

To be able to work on dashboards creation and to be able to enter dummies values, could you please create the "Increased value creation through traditional and non-traditional export value chains"data set with district level and quarter periodicity.

**Comment by arunimam** [comment]
Please confirm whether we need to create the data sets for all those indicators present under this indicator group
[Increased Value.xlsx](https://github.com/minagri-rwanda/DHIS2-Agriculture/files/304778/Increased.Value.xlsx)

Attached is the list of indicators under this indicator group

**Comment by Aleglise** [comment]
Yes. Please create Increased value creation through traditional and non-traditional export value chains dataset.

**Comment by arunimam** [comment]
Two Datasets have been created namely
1.Export Value Chains : Traditional & Non traditional District Level Quarterly Dataset
2.Export Value Chains : Traditional & Non traditional District Level Quarterly Dataset

We created two datasets because in the first dataset the indicators present are of type Outcome
and in the second dataset the indicator present are of type Output

These datasets have been assigned at district level and has been given a quarterly periodicity

PFA the excel for the same
[Export Value Chains.xlsx](https://github.com/minagri-rwanda/DHIS2-Agriculture/files/305459/Export.Value.Chains.xlsx)

**Comment by Aleglise** [comment]
Indicators do not have type like Outcome or Output.
This type is for indicator group only. So, it mean that indicator group are not properly defined.
In deed, the problem is that an Output and an Income do have the same name (Increased value creation through traditional and non-traditional export value chains).

Waiting for feedback from MINAGRI, I suggest to rename the indicator groups and data sets:
Increased value creation through traditional and non-traditional export value chains (Outcome)
Increased value creation through traditional and non-traditional export value chains (Output)

To avoid similar issue in future, please also check that every Impact, outcome, and output have distincts names (see issue #75)

**Comment by Aleglise** [comment]
Could you please also add
1/ stakeholder list
2/ baseline, target and progress for these indicators

![image](https://cloud.githubusercontent.com/assets/8737709/15937821/b82a8ad4-2e70-11e6-9bed-76274a3b7ae9.png)

**Comment by Aleglise** [comment]
Hello @arunimam 
Please find below the file with updated periodicity and level.
[13062016_Periodicity.Level.Missing.xlsx](https://github.com/minagri-rwanda/DHIS2-Agriculture/files/311450/13062016_Periodicity.Level.Missing.xlsx)

**Comment by arunimam** [comment]
sure, will incorporate

**Comment by arunimam** [comment]
Below are the indicator groups which belong to outcome and output both. So still the creation of indicator groups are pending.Please confirm how will we go ahead on this
1) Increased land productivity and climate change resilience through expanded access to irrigation systems
2) Improved provision of proximity and quality extension services according to local demand
3) Improved capacity of agricultural cooperatives to link farmers efficiently to input and output markets
4) An improved enabling environment for doing agribusiness and the business of smallholder farming
5) Increased value addition of food crops by producer organisations
6) Increased value creation through traditional and non-traditional export value chains
7) Increased capacities for quality management in market oriented apiculture 
8) Increased fiscal and technical agricultural decentralization
9) Establishment of a functionary border control system for im/exports
10) Strengthened information management for improved sector performance assessment
11) Youth and women adequately integrated within agricultural growth strategies
12) Increased environmental sustainability of agricultural production systems
13) Increased household capacities for dietary diversification and food utilization

**Comment by arunimam** [comment]
Also please confirm for the datasets which need to be created
There will be total 6 datasets

1.Baseline Outcome Export Value Chains Traditional & Non traditional District Level Quarterly   Dataset with target & progress restricted data entry
2.Target Outcome Export Value Chains Traditional & Non traditional District Level Quarterly Dataset with baseline & progress restricted data entry
3.Progress Outcome Export Value Chains Traditional & Non traditional District Level Quarterly Dataset with baseline & target restricted data entry
4. Baseline Output Export Value Chains Traditional & Non traditional District Level Quarterly Dataset
with target & progress restricted data entry
5.Target Output Export Value Chains Traditional & Non traditional District Level Quarterly Dataset
with baseline & progress restricted data entry
6.Progress Output Export Value Chains Traditional & Non traditional District Level Quarterly Dataset
with target & progress restricted data entry

If its fine then please confirm and we will go ahead and create it

**Comment by arunimam** [comment]
Now all the indicator groups are prefixed with Outcome,Impact & output

**Comment by Aleglise** [comment]
As suggested, adding the Result type in indicator groups and data sets name is ok.

Baseline, target and progress data sets should be created to let users demo_data_entry_baseline, demo_data_entry_target & demo_data_entry_progress perform baseline, target and progress data entry.

**Comment by arunimam** [comment]
All the above mentioned data sets have been created and are assigned at district level

Please check

**Comment by Aleglise** [comment]
Main structure si good. 

About (Outcome) Export Value Chains Traditional & Non traditional District Level Quarterly Dataset:
- Value of honey exports indicator should not be part of as it depends of "Increased capacities for quality management in market oriented apiculture" outcome
- If possible, avoid comma use in data element description

I do not have comment about Progress (Output) Export Value Chains Traditional & Non traditional District Level Quarterly Dataset.

Please create all the datasets.

**Comment by arunimam** [comment]
I have removed Value of Honey exports from the dataset
and Comma from the data element

All the above mentioned 6 datasets have been created
