### ISSUE TITLE
Why are there 5 approval workflows?

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#56]
What is the scope of "Province quarterly" ? In which case the "Province quarterly" workflow should be used? 
In which case the "Quarterly Approval-for Quarterly datasets" workflow should be used?

![image](https://cloud.githubusercontent.com/assets/8737709/15320748/76fc07ae-1c32-11e6-91f0-7d14aec03ce0.png)

**Comment by arunimam** [comment]
We are reworking on Approval workflows.

Will update the correct workflows by tomorrow

**Comment by Aleglise** [comment]
Ok. Please assign workflows at 3 different data entry levels (national, province & district).

**Comment by arunimam** [comment]
Now there are total 6 workflows- 
1) National Approval for Quarterly datatsets- To approve Province level data for quarterly datasets
2) National Approval for Yearly datasets- To approve Province level data for yearly datasets
3) Province Approval for Quarterly datasets- To approve District level data for quarterly datasets
4) Province Approval for Yearly datasets- To approve District level data for yearly datasets
5) District Approval for Quarterly datasets- To approve Sector level data for quarterly datasets
6) District Approval for Yearly datasets- To approve Sector level data for yearly datasets

All the workflows have been assigned to the datasets
One question who is going to approve National level data?

**Comment by Aleglise** [comment]
We need to approve National level data. According to http://dhis2.github.io/dhis2-docs/master/en/user/html/dhis2_user_manual_en_full.html#d0e9199 on the contrary of _Approve data at lower levels_, _Approve data_ authority allows that.
You should probably rename the role and create a new one according to authorities:
- Approve data at lower levels 
- Approve data

For information, for now there is no Sector level data entry. However, no need to delete workflows related to Sector level approval, it may be used later.

**Comment by Aleglise** [comment]
![image](https://cloud.githubusercontent.com/assets/8737709/15497973/8a87f81c-219d-11e6-9541-70da9df55423.png)

**Comment by arunimam** [comment]
We are unable to delete the approval levels from front end
Need to delete them from backend hence will take time
Once deleted levels and workflow will be recreated

In the meanwhile requesting you to check & confirm whether these approval workflow & levels are fine with you 

Approval levels : 
National at level 1
Province at level 2
District at level 3
Sector at level 4

Approval workflows:
Below six levels will be used for the approving the Province,District & Sector level data
Approve data at lower levels-District Quarterly
Approve data at lower levels-District Yearly
Approve data at lower levels-National Quarterly
Approve data at lower levels-National Yearly
Approve data at lower levels-Province Quarterly
Approve data at lower levels-Province Yearly
Below two levels will be used only for the approving the national level data
Approve data-Quarterly
Approve data-Yearly

**Comment by Aleglise** [comment]
OK with approval levels.

I do not understand the second part. Do you mean "workflows" instead of "levels"? Could you please clarify?

> Below six levels will be used for the approving the Province,District & Sector level data...

**Comment by arunimam** [comment]
now that all approvals are deleted, will create new with suggested names

**Comment by arunimam** [comment]
See there are two things in Approvals one is level which will approve the data second the workflows for defining who will approve whose data

As discussed there was an issue with approvals so deleted all the previously created approval levels and workflows , now will recreate again, so requesting you to kindly wait till tomorrow

**Comment by arunimam** [comment]
Levels & workflows have been created. You may please check
