### ISSUE TITLE
Shall gender disaggregation be managed with categories?

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#57]
Shall we manage gender disaggregation through Category or through distinct data elements?

2 options were offered to MINAGRI (M&F) and (CC) through 2 dataset definition in demo instance. 
Waiting MINAGRI feedback.

**Comment by abyot** [comment]
Yes, that is was my question in slack. If we also look into the other email from Tarik? (actually I have also talked with Tarik through phone). He mentioned to me that Collin has overused gender disaggregation...

**Comment by Aleglise** [comment]
@abyot Could you please provide more details about"the other email from Tarik"?

**Comment by Aleglise** [comment]
Abyot recommends to use 2 data elements ( solution M&F)

**Comment by Aleglise** [comment]
We finaly got client's feedback : the "M&F" option fits much better with MINAGRI's needs and reporting formats than the "CC" option. 

So please manage disaggregation with distinct data elements.

**Comment by arunimam** [comment]
So do we need to change the M&F distinct data elements for all those indicators who have the gender disaggregation?

**Comment by Aleglise** [comment]
Yes, indicators who have the gender disaggregation should have M&F distinct data elements.

**Comment by Aleglise** [comment]
@arunimam Following today's meeting, the only category to be used for every data element is Baseline&TargetandProgress.

No others category should be used.
