### ISSUE TITLE
Heterogenous Dataset sorting in project screen

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#58]
Budget forecast dataset & Budget execution dataset dropdown lists are not using the same sorting criteria

![image](https://cloud.githubusercontent.com/assets/8737709/15430431/a232096c-1ea5-11e6-807e-d9bd41ab3685.png)

![image](https://cloud.githubusercontent.com/assets/8737709/15430441/abedf6dc-1ea5-11e6-9271-a0f3fe17aa8c.png)

**Comment by abyot** [comment]
Fixed.
