### ISSUE TITLE
Supernumerary orgunits

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#6]
Why these orgunit groups are available ? I do not think that MINAGRI wil use them...

![image](https://cloud.githubusercontent.com/assets/8737709/14192287/05b208c8-f79d-11e5-8094-04ae96ee2118.png)

**Comment by Aleglise** [comment]
please remove facilities orgunit and related level and groups

**Comment by abyot** [comment]
This is fixed in dev.
