### ISSUE TITLE
Access to data approval - stakeholder selection

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#60]
After data entry
![selection_2016052311 45 44](https://cloud.githubusercontent.com/assets/8737709/15504469/73caeb44-21bf-11e6-9851-d6cb647bad3a.png)

and data analytics

Data to approve is not displayed when SPIU is selected whereas it should be displayed:
![selection_2016052414 08 16](https://cloud.githubusercontent.com/assets/8737709/15504520/af0641f4-21bf-11e6-9477-fe4ce6f8e735.png)

I noticed that if any other stakeholder is selected, data is displayed:
![image](https://cloud.githubusercontent.com/assets/8737709/15504562/de1f6696-21bf-11e6-8990-9eb3e013590b.png)

**Comment by abyot** [comment]
There is no approval currently. We need to recreate the whole thing.

**Comment by arunimam** [comment]
We are recreating the approval levels.

**Comment by Aleglise** [comment]
After data entry
![selection_2016060919 09 51](https://cloud.githubusercontent.com/assets/8737709/15939109/9fbfdb88-2e76-11e6-8fa9-095e5e68b861.png)

and running analytics

User demo_data_approval_province is not able to select the data set "Target(M&F)/Soil Conservation & Land Husbandry..."

**Comment by Aleglise** [comment]
@arunimam please provide a scenario of data set and users set to perform approval.

**Comment by Aleglise** [comment]
Again facing this issue with baseline data set:
After data entry
![image](https://cloud.githubusercontent.com/assets/8737709/16209920/a1209abe-3739-11e6-89ad-7da8d29565e6.png)
selection criteria:
![image](https://cloud.githubusercontent.com/assets/8737709/16209961/e196d9fa-3739-11e6-9d59-29768fdf5749.png)
and still nothing to approve:
![image](https://cloud.githubusercontent.com/assets/8737709/16209967/f43d8568-3739-11e6-96fd-9235f51b4c1e.png)

**Comment by abyot** [comment]
I am seeing data here

[image: Inline image 1]

---

Thank you,
Abyot.

**Comment by Aleglise** [comment]
Still having the issue (in demo instance):
![image](https://cloud.githubusercontent.com/assets/8737709/16210670/949ee5da-373d-11e6-8c5f-7317e0e114d8.png)

**Comment by abyot** [comment]
I only checked in dev. 

Are we sure we have the same db on dev and demo. I have updated demo (with db db) around lunch.

**Comment by Aleglise** [comment]
The issue is on Demo and Dev instances: 
Please check how I get this issue: https://drive.google.com/a/biosamples.co/file/d/0B9-HiXpk5KKkc1UwLVR6T2VQTGc/view?usp=sharing

**Comment by Aleglise** [comment]
Selecting the stakeholder for whichh there is data to approve mworks now but, if there is not data to approve, the "Approve" button is displayed and the number of items is equal to the number of stakeholders selected in the items selected.

![image](https://cloud.githubusercontent.com/assets/8737709/16422012/2ba27de2-3d57-11e6-9c37-3e0bbda69c2c.png)

**Comment by Aleglise** [comment]
Not able to reproduce.
