### ISSUE TITLE
Delete Approval Level

### ISSUE THREAD

**Issue by arunimam** [minagri-rwanda/DHIS2-Agriculture#61]
An approval level is wrongly created Sector. But when I try to delete it, it says "Failed to delete approval level

Kindly check and help me in deleting it. PFA screenshot

![image](https://cloud.githubusercontent.com/assets/12066960/15513194/477c834e-2201-11e6-9ae6-ae5a2c244262.png)

**Comment by arunimam** [comment]
Kindly delete all the approval levels & workflows. We need to recreate them. Not able to delete from front end

**Comment by abyot** [comment]
Everything related to approval is deleted.

**Comment by arunimam** [comment]
thanks abyot
