### ISSUE TITLE
Unable to select the stakeholder in DHIS2 Android App

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#63]
With user demo_data_entry_progress, I can access to DHIS2 Data Capture Android App, select an orgunit and a data set but I am not able to select the stakeholder whereas I should.

![screenshot_20160526-104804](https://cloud.githubusercontent.com/assets/8737709/15570959/b9e45398-2338-11e6-8db7-ad046749321d.png)

**Comment by abyot** [comment]
oh yes, that is not yet supported. will be supported in next release.

**Comment by Aleglise** [comment]
Do you mean that it will be supported in next release of the android app or DHIS2 for Rwanda MINAGRI?

**Comment by abyot** [comment]
I can't guarantee that. A different team is in charge of our android apps... often they are really busy and try their best to catch-up with the web-version. I am only hoping they will have this sometime soon.

**Comment by Aleglise** [comment]
Ok. So, you are talking about the Android App (see question above)? If yes, you can close the issue. If no, we have to talk about that..

**Comment by abyot** [comment]
Yes, it is about the Android app.
