### ISSUE TITLE
Unable to enter data

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#64]
With user demo_data_entry_progress, I am unable to enter data as it is impossible to select a stakeholder:

![selection_2016060111 11 15](https://cloud.githubusercontent.com/assets/8737709/15704295/50f49a26-27ea-11e6-996e-106db2b63d7f.png)

**Comment by abyot** [comment]
That is because the user group user "demo_data_entry_progress" belongs to did not have access to the stakeholder list.

If we know who should access what, we can do proper configuration in category option definition.

**Comment by Aleglise** [comment]
Could you please provide more detail about the configuration.

In Category option, I just see orgunit selection: http://62.210.124.144:9091/dev/dhis-web-maintenance/#/edit/dataElementSection/categoryOption/wkUHp1lWG2v?_k=a5jh63

**Comment by abyot** [comment]
I have been guiding HISP India team on this issue...  they should be able to solve this if you assign them the task.

In any case... right click category option -> Share then assign whichever user group you want access

**Comment by Aleglise** [comment]
I added 4 users groups to demo_data_entry_progress and it is ok now. Thank you.
![image](https://cloud.githubusercontent.com/assets/8737709/15739036/78578c6c-28ae-11e6-8e5c-8a1b13ddacf3.png)

**Comment by abyot** [comment]
Great.

But we have to be a bit careful here. We need to ask MINAGRI so that they provide us a proper list of who is accessing what.
