### ISSUE TITLE
Why entered data is not available for approval?

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#66]
The 1st of June data was entered:
![selection_2016060111 31 53](https://cloud.githubusercontent.com/assets/8737709/15737528/c4f2f5be-28a6-11e6-91b6-e901e91706ab.png)

Following issue #28 I waited for a night and 

The 2nd of June there nothing is displayed for approval (user demo_data_approval_province) but "Approve: 1 item" is displayed :
![selection_2016060209 44 14](https://cloud.githubusercontent.com/assets/8737709/15737574/0e5e80ce-28a7-11e6-99d2-910866c1f1ec.png)

But 

Does it mean that issue #28 is unsolved ? Is it a right issue ?

Thank you in advance

**Comment by arunimam** [comment]
Requesting to please Run the analytics and then check

**Comment by Aleglise** [comment]
Issue solved by running analytics
@abyot So, it means that analytics is not automatically executed during night
