### ISSUE TITLE
Progress report follow-up

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#68]
How to follow indicators of several outcomes in Performance contract ?

See examples:

A performance contract witj the indicators listed int the "Naeb" tab of the following file:
[199 Indicators included in MIS (2).xlsx](https://github.com/minagri-rwanda/DHIS2-Agriculture/files/300559/199.Indicators.included.in.MIS.2.xlsx)

or
[MINAGRI Imihigo 2016-2017 ok (2).xlsx](https://github.com/minagri-rwanda/DHIS2-Agriculture/files/300578/MINAGRI.Imihigo.2016-2017.ok.2.xlsx)

**Comment by abyot** [comment]
not sure I get you here - can you provide a specific template that I can look into?

By the way, the performance contract template we designed already caters for followup - Q1, Q2, Q3, Q4. Are we looking for more breakdowns?

**Comment by Aleglise** [comment]
Hello Abyot,
Actually, I've created a "NAEB indicators" called favorite table and would like to display the performance contract with the same indicators group.

**Comment by abyot** [comment]
What is special with this indicator group? can't we just create  a data set with corresponding baseline, target and progress data elements / dimensions and use the performance contract app? what blocked you from using this?

**Comment by Aleglise** [comment]
Thank you for your reply Abyot. This indicator group which has nothing special except the fact that NAEB users need to track it.

I don't know if it is possible or not to create a dedicated data set for that, as we are creating a Results typed(Impact, Outcome or Output) data set for every indicator group. That is why I've created the issue #69 

I do not think that we are looking for more breakdowns.

**Comment by abyot** [comment]
This I think we have discussed it. Somebody has to just create data set/data element and test out.

**Comment by Aleglise** [comment]
As discussed, an additional data set can be created to track specific data element through the performance contract app.
 As this new data set will be used for reporting only, it should be preferable to not use it for data entry (as it may lead to multiple data entry).

How this new data set should be set to use it for reporting purpose only?

**Comment by Aleglise** [comment]
These additional data set should be assigned to user who cannot perform data entry
