### ISSUE TITLE
Pivot Table favorite addition: indicators sorting changed after saving

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#70]
I saved a table with sorted selected indicators (NAEB Indicators). After saving, the first indicator is displayed as last.

Do I miss something in table setting ?

**Comment by arunimam** [comment]
Can we have a screen shot for the same

**Comment by Aleglise** [comment]
See https://drive.google.com/file/d/0B9-HiXpk5KKkVlNDX29WS3czeDg/view?usp=sharing

**Comment by arunimam** [comment]
Requesting Abyot to please check

**Comment by abyot** [comment]
Yes, I confirm that this is a bug which we have in standard DHIS 2. I have also reported this to the developer.
