### ISSUE TITLE
Error message when deleting a sub-program

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#72]
When deleting a sub-program, an unclear error message is displayed:

![image](https://cloud.githubusercontent.com/assets/8737709/15932615/b917544a-2e5c-11e6-9938-71fc41d014a8.png)

**Comment by abyot** [comment]
not able to reproduce. to facilitate debugging, it would be nice to send browser log every time when reporting such issues / bugs.

**Comment by Aleglise** [comment]
In future, I will send browser log when reporting such issues.

To reproduce, display sub program gLAEf9aeRc6 from "Program 1" Program and click on "Delete"

log:

> angular.js:87 DELETE http://62.210.124.144:9091/dev/api/subProgramms/gLAEf9aeRc6 500 (Erreur Interne de Servlet)(anonymous function) @ angular.js:87n @ angular.js:82f @ angular.js:80(anonymous function) @ angular.js:112$eval @ angular.js:126$digest @ angular.js:123$apply @ angular.js:126(anonymous function) @ angular.js:216dispatch @ jquery.min.js:2h @ jquery.min.js:2
