### ISSUE TITLE
Results framework : Unable to add several sub-programs to a program

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#73]
Adding sub-program to a program is not possible anymore

https://drive.google.com/file/d/0B9-HiXpk5KKkUXMwMW8zekYzVEE/view?usp=sharing

**Comment by abyot** [comment]
not able to reproduce. can you send your browser log?

**Comment by Aleglise** [comment]
Nothing special in log:
https://drive.google.com/file/d/0B9-HiXpk5KKkMmswMnEweHNXX0U/view?usp=sharing

**Comment by Aleglise** [comment]
Nothing special in log:
https://drive.google.com/file/d/0B9-HiXpk5KKkMmswMnEweHNXX0U/view?usp=sharing

**Comment by Aleglise** [comment]
@abyot After cache clearing, I still reproduce the issue. Please watch https://drive.google.com/file/d/0B9-HiXpk5KKkWk9fNFhwNVdzYm8/view?usp=sharing to reproduce.

Log

> Navigated to http://62.210.124.144:9091/dev/dhis-web-dashboard-integration/index.action
> dhis2.appcache.js?_rev=22005:50 Use of the Application Cache is deprecated on insecure origins. Support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
> Navigated to http://62.210.124.144:9091/dev/dhis-web-results-framework/index.html
> results-framework.js:129 Loading required meta-data
> results-framework.js:179 Finished loading meta-data
> results-framework.js:129 Loading required meta-data
> results-framework.js:179 Finished loading meta-data

**Comment by Aleglise** [comment]
@abyot It seems that this issue does not reproduced when code and name do not contain the dot (".") caracter (see "MINAGRI RF" Results Framework programs). Is there a limitation there? Thank you for your reply.

**Comment by Aleglise** [comment]
Walk around so priority decreased
