### ISSUE TITLE
Output defined as an outcome

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#74]
Indicator group "Increased land productivity and climate change resilience through expanded access to irrigation systems" is defined as an outcome whereas it should be defined as an output

**Comment by arunimam** [comment]
In this indicator group there are total 5 indicators , out of these 5 , 2 are outcome & 3 are output. Can you please tell how we should go ahead for this?

**Comment by Aleglise** [comment]
The fact is that there are 2 indicator groups 1.0.3 and 1.2.1.2 (see issue #75 )

**Comment by arunimam** [comment]
So the indicator groups which have duplicate types should be created as
Outcome-Indicator group name
Output-Indicator group name

**Comment by Aleglise** [comment]
Yes. 
Please be homogenic in naming convention (see issue #55 last comments).

**Comment by arunimam** [comment]
All the indicator groups have been renamed as

Impact-Indicator Group Name
Outcome-Indicator Group Name
Output-Indicator Group Name
