### ISSUE TITLE
Incorrect indicators definition

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#79]
Following issue #77 it seems that Indicator like "Annual yield of climbing beans crops" or Annual yield of cassava crops are not defined as client asked in file Annex 2.2_Monitoring Framework_2015.12.18_part 2_(Alina).xlsx

Please check every indicator definition and correct when required.

**Comment by arunimam** [comment]
Can you please clarify where we need to define the indicators

**Comment by Aleglise** [comment]
Indicators should be defined as Annex 2.2_Monitoring Framework_2015.12.18_part 2_(Alina).xlsx

Annual yield of climbing beans crops indicator should be defined according to "1.0.4.3 climbing beans yield" tab of Annex 2.2_Monitoring Framework_2015.12.18_part 2_(Alina).xlsx

According to issue #77 there are indicator definition gaps

**Comment by arunimam** [comment]
I have checked in the application, the indicator Annual yield of climbing beans & Annual yield of cassava crops are defined correctly according to the Annex 2.2_Monitoring Framework_2015.12.18_part 2_(Alina).xlsx sheet

In Part 2 sheet : The numerator in this indicator is Production in tonnes and denominator is Harvested Area

In the application the numerator is Production in tonnes (Climbing beans) -this is a category combination data element and the denominator is Harvested Area

![image](https://cloud.githubusercontent.com/assets/12066960/16092140/2f42920a-3354-11e6-91e9-540e30ab9df4.png)

![image](https://cloud.githubusercontent.com/assets/12066960/16092152/3969fab6-3354-11e6-8777-5d8bcebbabd5.png)

**Comment by Aleglise** [comment]
Now it is correct : http://62.210.124.144:9091/dev/api/indicators.json?fields=name,code,id,numerator,numeratorDescription,denominator,denominatorDescription,indicatorType,indicatorGroups&paging=false

> {"code":"1.0.4.3","name":"Annual yield of climbing beans crops","id":"tjYocN7xMHs","denominatorDescription":"Harvested Area","numerator":"#{QWtwx5G8gRh.DIMru73k9qG}","numeratorDescription":"Production in tonnes (Climbing beans)","denominator":"#{zGNARGlZwp4.icy8rm0bnbr}","indicatorType":{"id":"YWmE11iMhiT"},"indicatorGroups":[{"id":"klPHrm5QUAJ"}]},
