### ISSUE TITLE
Outputs not available for inactive results framework's sub programs

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#82]
Following issue #1 when an output is assigned to a sub program, it is not displayed for others sub programs. This is because a sub-program cannot be linked to several sub-program of a Results framework.

However, this limitation should not apply for another result framework 
example:  
output A is assigned to RF1 sub-program 1.1
when accessing to RF1 sub-program 1.2, output A is not available for assigment --> OK
when accessing to RF2 sub-program 1.1 output A is currently not available for assigment whereas it should.

Results assigment limitation should be active within a results framework but not amng several results framework.

A walk around is possible for now through RF1 desactivation but it would be preferable to fix this issue to let user work on a new RFR without desactivate the current active one.

**Comment by abyot** [comment]
I need a confirmation from Thierry on this.

**Comment by Aleglise** [comment]
We leave that.
