### ISSUE TITLE
Results framework activation: Wrong message label

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#85]
Clicking on "Activate",
![image](https://cloud.githubusercontent.com/assets/8737709/16044713/df301bac-3245-11e6-9167-6c644f7bfdcc.png)

 the following message is displayed

> Activate
> Are you sure you want to deactivate?

whereas the message should be "Are you sure you want to activate?"

![image](https://cloud.githubusercontent.com/assets/8737709/16044742/f1fe305c-3245-11e6-8e6a-3a23205aac9c.png)

**Comment by abyot** [comment]
Fixed.
