### ISSUE TITLE
Missing indicators / indicator to be renamed

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#86]
Afer creating MINAGRI RF and having done a comparison, it seems that 14 indicators need to be created or renamed (see attached file )
[RF MINAGRI.xlsx](https://github.com/minagri-rwanda/DHIS2-Agriculture/files/314134/RF.MINAGRI.xlsx)

**Comment by arunimam** [comment]
Attached are the remarks
[RF.MINAGRI.xlsx](https://github.com/minagri-rwanda/DHIS2-Agriculture/files/316920/RF.MINAGRI.xlsx)
, kindly check

**Comment by Aleglise** [comment]
The Impact "Vision 2020 and EDPRS-2 targets for economic growth and poverty reduction are supported adequately by the agriculture sector" was added to MINAGRI RF. However, the indicator Annual value added per rural household from cropping and livestock keeping is not displayed. Please check again. Thank you.

![image](https://cloud.githubusercontent.com/assets/8737709/16096509/a201c5e6-3349-11e6-806d-6034d1aba761.png)

![image](https://cloud.githubusercontent.com/assets/8737709/16096608/10ddbe02-334a-11e6-817f-e2d3e1e0a1ff.png)

**Comment by arunimam** [comment]
Indicator added to the group, please check

**Comment by Aleglise** [comment]
1 indicator was added but 11 are still missing (see 
[20160616_RF_MINAGRI.xlsx](https://github.com/minagri-rwanda/DHIS2-Agriculture/files/317994/20160616_RF_MINAGRI.xlsx)
 )

**Comment by arunimam** [comment]
Can you please tell where you are not able to see these 11 indicators

**Comment by Aleglise** [comment]
I am not able to see these indicators in Results Framework Apps (Apps>Results Framework), on the page displayed when you click on MINAGRI_RF and select "Overview":
https://cloud.githubusercontent.com/assets/8737709/16096509/a201c5e6-3349-11e6-806d-6034d1aba761.png

https://cloud.githubusercontent.com/assets/8737709/16096608/10ddbe02-334a-11e6-817f-e2d3e1e0a1ff.png
