### ISSUE TITLE
Pivot table data display issue

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#87]
I've created a pivot table favorite called Data entry 02 which does not display data whereas we are expecting data to be displayed. 

Adding an additional period seems to offer a walk around and to solve the problem (see favorite Data entry 04)

**Comment by abyot** [comment]
I am not sure, I understand the issue here. If assigning additional period displays data, this means the previously assigned period does not have data. I do not think this is a bug.

**Comment by Aleglise** [comment]
Ok thanks. Let it be.
