### ISSUE TITLE
Surnumerical orgunits

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#88]
3 districts are on the same level than Rwanda whereas they should not
![selection_2016061615 20 05](https://cloud.githubusercontent.com/assets/8737709/16118151/0cebc8c0-33d6-11e6-9e6d-66c64d8f2828.png)

**Comment by Aleglise** [comment]
Why did you assigned the issue to me Abyot ?
Is there a link with issue #100? If yes, simply close this issue.

**Comment by abyot** [comment]
I assigned it you because last time you mentioned you want to check and close issues.

**Comment by Aleglise** [comment]
ok.
