### ISSUE TITLE
Why data element history does not display previous entered data?

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#89]
For 2015Q2&3, there are approved data for area of well maintained terraces of a male headed household.

Why double clicking on the data element does not lead to the history display?

![image](https://cloud.githubusercontent.com/assets/8737709/16127526/273ecf0c-33fd-11e6-8521-dec17412311d.png)

**Comment by abyot** [comment]
There was a bug. Now fixed.

![image](https://cloud.githubusercontent.com/assets/4967749/16356847/3a75e124-3ae6-11e6-8353-a03ebe5031dd.png)
