### ISSUE TITLE
Target and progress are missing for areas for  Soil Conservation and Land Husbandry District Level Quarterly Dataset ?

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#9]
![selection_2016040412 03 20](https://cloud.githubusercontent.com/assets/8737709/14244794/5e21f9ce-fa5d-11e5-9d5a-f17fea3af196.png)

When entering data for Soil Conservation and Land Husbandry District Level Quarterly Dataset, there are 2 field for male and female whereas when should have distinct data sets for progress and target...

**Comment by arunimam** [comment]
Issue no. 9 reported for dataset Soil Conservation & land Husbandry District Level Quarterly Dataset has been created for the indicators

Tab no. 1.1.1 1: Total & Percentage of land area developed with well maintained progressive and bench terracing structures
Num & Den: Female/male headed households area of well maintained terraces/Total potential area of female/male headed households of all types of terraces

Tab no. 1.1.1 2: Total area & Percentage of land developed with progressive terraces
Num & Den Female/male headed households area of progressive terraces/Total potential area of female/male headed households of all types of terraces

Tab no. 1.1.1 3: Total area & Percentage of land developed with bench terraces based on standard pH > 5.2 and handed over  
Num & Den : Area of bench terraces handed over to female/male headed households/Total area of bench terraces allocated to female/male headed households 

So based on these numerator & denominator it is disaggregated into Male headed & Female headed households

All are output indicators with same periodicity & level

But if we want to create by target & progress for both numerator & denominator it would be:

Target Area (Male headed household) & Target (Female headed household)
Progress Area (Male headed household) & Progress Area (Female headed household)

But please confirm will it be a separate dataset for progress and separate for target or one dataset for both?

**Comment by Aleglise** [comment]
You are right for gender disaggregation. So input have to be performed per gender. 

About progress and target, according to the specification, the business need is to have some users to be able to enter target and others to enter progress. For the last demo, we created 2 datasets (one for target & one for progress, see https://drive.google.com/open?id=0B9-HiXpk5KKkRUVDaXZERWhYa0E). If only one dataset fullfills this requirement, it would be simpler and therefore better. If it is not possible, then we need 2 data sets.

**Comment by arunimam** [comment]
As required target & progress both along with gender are added in Soil Conservation & land Husbandry District Level Quarterly Dataset

**Comment by Aleglise** [comment]
OK. How restrict access to Target & Progress to 2 groups of users (target data entry users & progress data entry users) ?

**Comment by arunimam** [comment]
two seperate data sets have been created assigned at district level

Target-Soil Conservation & Land Husbandry District Level Quarterly Dataset
Progress-Soil Conservation & Land Husbandry District Level Quarterly Dataset

**Comment by Aleglise** [comment]
As specified in https://docs.google.com/document/d/1YLW9LYA-zkXmqeC1hOw66ONH-nxK7VlS8jLmeNRH66k/edit#heading=h.48pi1tg and show in https://drive.google.com/open?id=0B9-HiXpk5KKkRUVDaXZERWhYa0E target and progress should be displayed in dataset. Please update.

**Comment by Aleglise** [comment]
I saw that you created 2 data element for "area of well maintained terraces" (one for Progress and another for target). Why Progress and target are not defined as a category options as we did for demo 01 ?

**Comment by Aleglise** [comment]
I saw that you created Households & Target&Progess category combination. Why is it not applied to data element ?

**Comment by arunimam** [comment]
completed

**Comment by Aleglise** [comment]
User demo_data_entry_target can input target data in Target-Soil Conservation and Land Husbandry District Level Quarterly Dataset. That is fine.

But user demo_data_entry cannot input progress data in Soil Conservation and Land Husbandry District Level Quarterly Dataset whereas he should be able to do it.

In future, after fixing an issue, please assign issue to me instead of closing it. it will allow me to restest the issue. thank you.

**Comment by arunimam** [comment]
noted

**Comment by arunimam** [comment]
this is because, the presumption is that the person who adds targets should might be different from the person who enters progress, and the one adding target should not be edited by anyone. so the person adding progress can see the target but cannot add / edit target

**Comment by Aleglise** [comment]
Following today meeting, please add a second dataset for Soil Conservation and Land Husbandry District Level Quarterly Dataset Progress for user user demo_data_entry

**Comment by arunimam** [comment]
dataset created, pls check

**Comment by Aleglise** [comment]
Good. Thank you. I updated user role "Data Entry Progress" adding this new dataset created.
