### ISSUE TITLE
Data sets creation 

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#91]
Now that issue #55 is solved, please create every data set required to manage MINAGRI indicators listed in  Annex 2.2_Monitoring Framework_2015.12.18_part 1_(Alina).xlsx and Annex 2.2_Monitoring Framework_2015.12.18_part 2_(Alina).xlsx

**Comment by Aleglise** [comment]
@arunimam  Please create all data sets using Export Value Chains Traditional & Non traditional District Level Quarterly Dataset as a template.

**Comment by arunimam** [comment]
@Alex  please confirm one thing that do we need to make Baseline ,Target & Progress datasets for all the indicators...which means every indicator will have three datasets

**Comment by Aleglise** [comment]
@arunimam yes. I confirm that.

**Comment by arunimam** [comment]
@ Alex

PFA the excel sheet with datatsets name 
Requesting you to please check & confirm the dataset names as per client's requirements:

1) All indicators will have three datasets : Baseline,Progress & Target
2) Outcome & Impact type of indicators will have their results in the name of the dataset
3) Output type of indicators will have their sub programs in the name of the dataset
4) All gender dis aggregated indicators will have distinct data elements for male & female
5) There will be only one category i.e Baseline/Target/Progress and rest all the categories need to be removed
All the above points have been kept in mind while making the names of the dataset

Also please confirm one thing there are near about 24 indicators which have dual periodicity Quarterly & Annual, so either the periodicity can be Annual or it can be Quarterly, we need clarification on this
[Dataset Names.xlsx](https://github.com/minagri-rwanda/DHIS2-Agriculture/files/326486/Dataset.Names.xlsx)

So please check this excel sheet and give a confirmation to go ahead for creating datasets in the application.

**Comment by Aleglise** [comment]
I will ask to client to confirm these information and provide clarification.

Issue #55 does not provide you enough infomation?

**Comment by arunimam** [comment]
Once if it is confirmed from client it will be better to create these in the application. These are 597 datasets, so huge lots of work. Confirmation is better rather than redoing the work

**Comment by Aleglise** [comment]
For baseline and target data sets you should allow future periods entry (for the following year)

**Comment by Aleglise** [comment]
Actually for output data set should have the name of the result, not of the sub-program
So data set should have the name of the result (as indicator groups).
ex. Target(Outcome) Export Value Chains Traditional & Non traditional District Level Quarterly Dataset
Should be name Target (Outcome) Increased value creation through traditional and non-traditional export value chains

If the data set name is too long, you can use OC for Outcome, OP for Output and IP for Impact. 

ex. Target OC Increased value creation through traditional and non-traditional export value chains instead of Target (Outcome) Increased value creation through traditional and non-traditional export value chains

**Comment by Aleglise** [comment]
@abyot 
Indeed client needs for each results 2 data sets:
1 for progress entry (as existing progress data sets)
1 for baseline and target data entry (the 2 category options in the same data set with will be entered in the same time by the same user and which will also be approved in the same time by the approver)

But what has been designed for performance contract prevent to merge baseline and progress data sets right?

**Comment by arunimam** [comment]
@Aleglise 
So now you are saying that Output indicators will have their name of the results in their dataset name and Impact & Outcome will have their sub program name

**Comment by arunimam** [comment]
But let me clear one thing that Impact & Outcome indicators doesn't have the sub program name in Alina part 1 & 2 sheets...Only output indicators have their sub program name

**Comment by Aleglise** [comment]
@arunimam wee need to discuss about that. I sent again the invitation for the user acceptance test 4pm CEST daily call.

**Comment by Aleglise** [comment]
@arunimam we need to discuss about that asap

1) All **results** will have three datasets : Baseline,Progress & Target with every indicator of the dataset
2) The data set should be name according to the result name
3) For each result, an indicator group should be created with all the result indicators. The indicator group name should be the same than the result name
4) All disaggregated indicators will have distinct data elements
5) There will be only one category _**for indicators_\* i.e Baseline/Target/Progress  and two categories for Budget (budget type and budget source) and rest all the categories need to be removed

If the data set names are too long, you can use OC for Outcome, OP for Output and IP for Impact.
ex. Target OC Increased value creation through traditional and non-traditional export value chains instead of Target (Outcome) Increased value creation through traditional and non-traditional export value chains

**Comment by Aleglise** [comment]
Client provided frequencies for listed indicators:
[20160626Dataset.Names.xlsx](https://github.com/minagri-rwanda/DHIS2-Agriculture/files/332000/20160626Dataset.Names.xlsx)

**Comment by Aleglise** [comment]
Please create the following data sets in priority:

OC Research and technology transfer and extension and proximity services
OC Improved provision of proximity and quality extension services according to local demand
OC Increased capacity of farmers for efficient, productive and sustainable use of agricultural technology
OP Increased coverage, efficiency and sustainability of soil conservation infrastructure and practices
OP Increased availability of technologies to increase the productivity, quality and resilience of food and export crops
OP Improved provision of proximity and quality extension services according to local demand
OP Increased availability and affordability of animal protein for vulnerable households

Client need them for User Test Acceptance

Thank you.

**Comment by arunimam** [comment]
Following Datasets have been created

**OC Research and technology transfer and extension and proximity services**
- 1) Baseline (OC) Research & Technology Transfer & Extension & Proximity Services District Level   Annual Dataset
  -    2) Progress (OC) Research & Technology Transfer & Extension & Proximity Services District Level Annual Dataset
  -   3) Target (OC) Research & Technology Transfer & Extension & Proximity Services District Level Annual Dataset
  - 4) Baseline (OC) Research & Technology Transfer & Extension & Proximity Services District Sector Level Quarterly Dataset
  - 5) Progress (OC) Research & Technology Transfer & Extension & Proximity Services District Sector Level Quarterly Dataset
  - 6)  Target (OC) Research & Technology Transfer & Extension & Proximity Services District Sector Level Quarterly Dataset

**OP Improved provision of proximity and quality extension services according to local demand**
- 1) Baseline (OP) Improved Provision of Proximity & Quality Extension Services according to Local Demand District Level Quarterly Dataset
- 2) Progress (OP) Improved Provision of Proximity & Quality Extension Services according to Local Demand District Level Quarterly Dataset
- 3) Target (OP) Improved Provision of Proximity & Quality Extension Services according to Local Demand District Level Quarterly Dataset
- 4) Baseline (OP) Improved Provision of Proximity & Quality Extension Services according to Local Demand District Sector Level Quarterly Dataset
- 5) Progress (OP) Improved Provision of Proximity & Quality Extension Services according to Local Demand District Sector Level Quarterly Dataset
- 6) Target (OP) Improved Provision of Proximity & Quality Extension Services according to Local Demand District Sector Level Quarterly Dataset
- 7) Baseline (OP) Improved Provision of Proximity & Quality Extension Services according to Local Demand National Level Annual Dataset
- 8) Progress (OP) Improved Provision of Proximity & Quality Extension Services according to Local Demand National Level Annual Dataset
- 9) Target (OP) Improved Provision of Proximity & Quality Extension Services according to Local Demand National Level Annual Dataset

**Comment by arunimam** [comment]
Some more datasets which have been created are

**Impact-Vision 2020 and EDPRS-2 targets for economic growth and poverty reduction supported by agriculture sector**

1) Baseline (IP)-Vision 2020 and EDPRS-2 targets for economic growth and poverty reduction supported by agriculture sector National Level Annual Dataset
2) Progress (IP)-Vision 2020 and EDPRS-2 targets for economic growth and poverty reduction supported by agriculture sector National Level Annual Dataset
3) Target (IP)-Vision 2020 and EDPRS-2 targets for economic growth and poverty reduction supported by agriculture sector National Level Annual Dataset

**Comment by Aleglise** [comment]
@arunimam For now, data collection will not occur on lower level than district.
You should therefore not create "District Sector" data sets.

**Comment by arunimam** [comment]
Ok sure I will do the changes

**Comment by arunimam** [comment]
Though i have not assigned the datasets to Sector. Let the names remain like this. If it is OK for you

**Comment by arunimam** [comment]
Following datasets have been created

**OC Increased capacity of farmers for efficient, productive and sustainable use of agricultural technology**

1) Baseline (OC) Increased Capacity of Farmers for Efficient,Productive & Sustainable Use of Agricultural Technology District Level Quarterly Dataset
2) Progress (OC) Increased Capacity of Farmers for Efficient,Productive & Sustainable Use of Agricultural Technology District Level Quarterly Dataset
3) Target (OC) Increased Capacity of Farmers for Efficient,Productive & Sustainable Use of Agricultural Technology District Level Quarterly Dataset

**OP Increased coverage, efficiency and sustainability of soil conservation infrastructure and practices**
1) Baseline (OP) Increased Coverage,Efficiency & Sustainability of Soil Conservation Infrastructure & Practices District Level Quarterly Dataset
2) Progress (OP) Increased Coverage,Efficiency & Sustainability of Soil Conservation Infrastructure & Practices District Level Quarterly Dataset
3) Target (OP) Increased Coverage,Efficiency & Sustainability of Soil Conservation Infrastructure & Practices District Level Quarterly Dataset

**Comment by arunimam** [comment]
Not able to create any dataset , getting exception error after saving the dataset

Kindly create any custom dataset & then press Save&Close button. Please check

![image](https://cloud.githubusercontent.com/assets/12066960/16454000/7adf8852-3e2c-11e6-871c-14f2cb65940c.png)

**Comment by abyot** [comment]
@arunimam  Can you provide more input here? which data set should I check?

I just created a sample data set. see here http://62.210.124.144:9091/dev/dhis-web-maintenance-dataset/editDataSetForm.action?dataSetId=7203

and it is working.

**Comment by arunimam** [comment]
Yes even i am able to save the dataset you have created

I am facing this issue in the dataset

Baseline (OP) Increased Availability of Technologies to Increase the Productivity, Quality and Resilience of Food and Export Crops District Level Quarterly Dataset

Designed the data entry form
![image](https://cloud.githubusercontent.com/assets/12066960/16455316/8048c8da-3e31-11e6-9655-c0ea873f2320.png)

Click on Save & Close button-Getting exception error

![image](https://cloud.githubusercontent.com/assets/12066960/16455354/9b2fcc70-3e31-11e6-880b-bddc2de5ff71.png)

**Comment by arunimam** [comment]
@Aleglise 
The lengthy dataset names are giving exception error in creating datasets due to fixed character limit
Can we cut short the name of the result type?

**Comment by abyot** [comment]
Maximum character length - as it stands in DHIS 2 - we can have for names is 230 chars.

**Comment by Aleglise** [comment]
Yes, as the limit is 230 chars. and as you have to create the data set, you have to short cut data sets name.

However "Baseline (OP) Increased Availability of Technologies to Increase the Productivity, Quality and Resilience of Food and Export Crops District Level Quarterly Dataset" has 163 chars. only.

May it be linked to the comma ?

**Comment by abyot** [comment]
no earlier it was 160, just changed it to 230 (which is the max we have in other places).

**Comment by Aleglise** [comment]
ok great.

**Comment by arunimam** [comment]
Following datasets have been created and assigned at respective levels

**OP Increased availability of technologies to increase the productivity, quality and resilience of food and export crops**

1)Baseline (OP) Increased Availability of Technologies to Increase the Productivity, Quality and Resilience of Food and Export Crops District Level Quarterly Dataset
2) Progress (OP) Increased Availability of Technologies to Increase the Productivity, Quality and Resilience of Food and Export Crops District Level Quarterly Dataset
3) Target (OP) Increased Availability of Technologies to Increase the Productivity, Quality and Resilience of Food and Export Crops District Level Quarterly Dataset
4) Baseline (OP) Increased Availability of Technologies to Increase the Productivity, Quality and Resilience of Food and Export Crops National Level Quarterly Dataset
5) Progress (OP) Increased Availability of Technologies to Increase the Productivity, Quality and Resilience of Food and Export Crops National Level Quarterly Dataset
6) Target (OP) Increased Availability of Technologies to Increase the Productivity, Quality and Resilience of Food and Export Crops National Level Quarterly Dataset

**OC Improved provision of proximity and quality extension services according to local demand**

1) Baseline (OC) Improved Provision of Proximity and Quality Extension Services according to Local Demand District Sector Level Quarterly Dataset
2) Target (OC) Improved Provision of Proximity and Quality Extension Services according to Local Demand District Sector Level Quarterly Dataset
3) Progress (OC) Improved Provision of Proximity and Quality Extension Services according to Local Demand District Sector Level Quarterly Dataset

 **(OP) Improved Provision of Proximity & Quality Extension Services according to Local Demand District Sector Level Quarterly Dataset**

1) Baseline (OP) Improved Provision of Proximity & Quality Extension Services according to Local Demand District Level Quarterly Dataset
2) Target (OP) Improved Provision of Proximity & Quality Extension Services according to Local Demand District Level Quarterly Dataset
3) Progress (OP) Improved Provision of Proximity & Quality Extension Services according to Local Demand District Level Quarterly Dataset
4) Baseline (OP) Improved Provision of Proximity & Quality Extension Services according to Local Demand District Sector Level Quarterly Dataset
5) Target (OP) Improved Provision of Proximity & Quality Extension Services according to Local Demand District Sector Level Quarterly Dataset
6) Progress (OP) Improved Provision of Proximity & Quality Extension Services according to Local Demand District Sector Level Quarterly Dataset
7) Baseline (OP) Improved Provision of Proximity & Quality Extension Services according to Local Demand National Level Annual Dataset
8) Target (OP) Improved Provision of Proximity & Quality Extension Services according to Local Demand National Level Annual Dataset
9) Progress (OP) Improved Provision of Proximity & Quality Extension Services according to Local Demand National Level Annual Dataset

**OP Increased availability and affordability of animal protein for vulnerable households**

1) Baseline (OP) Increased Availability & Affordability of Animal Protein for Vulnerable Households District Level Quarterly Dataset
2) Target (OP) Increased Availability & Affordability of Animal Protein for Vulnerable Households District Level Quarterly Dataset
3) Progress (OP) Increased Availability & Affordability of Animal Protein for Vulnerable Households District Level Quarterly Dataset
4) Baseline (OP) Increased Availability & Affordability of Animal Protein for Vulnerable Households National Level Annual Dataset
5) Target (OP) Increased Availability & Affordability of Animal Protein for Vulnerable Households National Level Annual Dataset
6) Progress (OP) Increased Availability & Affordability of Animal Protein for Vulnerable Households National Level Annual Dataset

**Comment by Aleglise** [comment]
@arunimam Next priority data sets to create for user test acceptance are:

OP Increased land productivity and climate change resilience through expanded access to irrigation systems
OP Increased self-reliance and technical capacity of Water User Associations
OP Improved capacity of agricultural cooperatives to link farmers efficiently to input and output markets
OP Reduced trading across border costs
OP Increased value creation through traditional and non-traditional export value chains
OP Increased availability and improved utilization of financial services in the agriculture sector
OP Reduced post-harvest losses in staple food crops
OP Reduced transport costs to market agricultural produce

**Comment by Aleglise** [comment]
@arunimam 
Progress (OP) Improved Provision of Proximity & Quality Extension Services according to Local Demand National Level Annual Dataset & Progress (OP) Improved Provision of Proximity & Quality Extension Services according to Local Demand District Sector Level Quarterly Dataset does not exist.

And there are Progress (OP) Increase Provision... data set. Did you missed the naming of these data sets?

**Comment by Aleglise** [comment]
@arunimam For next data sets creation please assign Stakeholder instead of stakeholder list.

**Comment by arunimam** [comment]
Name of the dataset has been corrected now, changed to Improved from Increased
