### ISSUE TITLE
Data approval fail

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#93]
After having perfom data entry:
![image](https://cloud.githubusercontent.com/assets/8737709/16208864/7863a04e-3734-11e6-98d2-158252bb50ae.png)
I go to data approval and using these criteria
![image](https://cloud.githubusercontent.com/assets/8737709/16208911/bf3285bc-3734-11e6-8b65-f432940afaa3.png)
I do not see any data to approve and "1 items" is display
![image](https://cloud.githubusercontent.com/assets/8737709/16208927/de47d588-3734-11e6-8b44-12a42b311a29.png)

If it may help you to solve this bug, after selecting 4 stakeholder, "4 items" is displayed:

![image](https://cloud.githubusercontent.com/assets/8737709/16208978/1d890820-3735-11e6-9274-19bcade064cc.png)

**Comment by arunimam** [comment]
Please check the data entered is of 2013 and in data approval you are taking the first quarter Jan-March 2103, you need to select last quarter i.e Oct-Dec 2013, the data will be shown in last quarter (the quarter gone by) of previous years and same for current year means data will be shown in the quarter gone by

![image](https://cloud.githubusercontent.com/assets/12066960/16209316/1d76f3d2-3754-11e6-8b6e-6cc92fc1e36d.png)

**Comment by arunimam** [comment]
![image](https://cloud.githubusercontent.com/assets/12066960/16209357/435daa32-3754-11e6-92df-c864d6280d2d.png)

**Comment by Aleglise** [comment]
Actually I was following the provided SOP:
![image](https://cloud.githubusercontent.com/assets/8737709/16209448/61f59530-3737-11e6-89a2-8fd9f6a53b28.png)

**Comment by arunimam** [comment]
Ok no issues i will update the same in the SOP's

**Comment by arunimam** [comment]
PFA the updated SOP
[SOPs for Data Entry & Approval.docx](https://github.com/minagri-rwanda/DHIS2-Agriculture/files/326212/SOPs.for.Data.Entry.Approval.docx)

**Comment by Aleglise** [comment]
After having perform baseline data entry:
![selection_2016062122 33 29](https://cloud.githubusercontent.com/assets/8737709/16245463/5372990c-3801-11e6-8b4c-7b05cf50330f.png)
I access to data approval
![selection_2016062122 39 25](https://cloud.githubusercontent.com/assets/8737709/16245484/6b02f594-3801-11e6-84f7-76c6e064c953.png)

For your information I've updated demo_data_entry_baseline user and Data_entry_Baseline user role to remive surnumerical data sets

**Comment by arunimam** [comment]
I didn't understand what is the issue you are facing? Can you please elaborate a little

Data is visible in data approval

![image](https://cloud.githubusercontent.com/assets/12066960/16260779/8290b3ce-3886-11e6-914b-f920db3feb1e.png)

**Comment by Aleglise** [comment]
I can see it now. I may have forgot to run analytics... o_O
