### ISSUE TITLE
Data sets not available for approval

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#94]
Several data sets are not available for data selection for approval ex. Target(Outcome) Export Value Chains Traditional & Non traditional District Level Quarterly Dataset

Data set field of http://62.210.124.144:9091/dev/dhis-web-reporting/showDataApprovalForm.action:
![image](https://cloud.githubusercontent.com/assets/8737709/16209628/24610334-3738-11e6-8b0f-a0f669e75a06.png)

**Comment by arunimam** [comment]
Please check the datasets are visible now. But before checking clear the cache & cookies of your browser

![image](https://cloud.githubusercontent.com/assets/12066960/16215816/e8297cb6-3782-11e6-88f1-fdb0a3b23e3e.png)

**Comment by abyot** [comment]
The problem was data sets were fetching in a paging. This is now fixed.
