### ISSUE TITLE
Maps - Coordinates could not be loaded

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#98]
You can check oin demo instance. The error message appears when opening the "Belyse" pivot table as a map.
[Screenshort Error.docx](https://github.com/minagri-rwanda/DHIS2-Agriculture/files/327077/Screenshort.Error.docx)

**Comment by abyot** [comment]
What are the parameters you selected?

**Comment by Aleglise** [comment]
What parameters? If you open favorite table, you cannot see it?
To reproduce:
Access to demo instance
Access to pivot table
Open "Belyse" Favorite
Click "Map" and "Open this table as Map"

Actually today the error is different: "No value"

**Comment by abyot** [comment]
"Belyse" has 
- 4 indicators / dataelements
- Last 12 months
- Last 5 years
- Kicukiro District

selected as parameters - this is fine for pivot. but not for maps.

In maps we can only interpret a single data (data element or indicator) using two dimensions. The first dimension is period (has to be a single period !) the second dimension is area.

**Comment by Aleglise** [comment]
thanks
